{{- if .Values.secret.enabled }}
{{- $secretConfig := dict
  "secret" (dict
    "name" .Values.secret.name
    "data" .Values.secret.data
  )
-}}
{{ include "library.secret" $secretConfig | nindent 0 }}
{{- end }}