replicaCount: 1
enabled: true

image:
  repository: "sumery/auth"
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    http:
      enabled: true
      port: 30001
      targetPort: 30001
    grpc:
      enabled: false
      port: 30002
      targetPort: 30002

env:
  - name: DB_SOURCE
    valueFrom:
      secretKeyRef:
        name: ecommerce-db-secret
        key: DB_SOURCE

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

secret:
  enabled: true
  name: "ecommerce-db-secret"
  data:
    DB_SOURCE: "" # Base64 值通过父 Chart 或命令行注入
