apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/ecommerce-frontend
    newTag: "1.7.7"
    digest: sha256:02dea7eb72bf67344c659bb241c9d846d3b2803a14a2b1ec8ebd039e52e6581a
