apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/ecommerce-frontend
    newTag: "1.7.4"
    digest: sha256:91709d1c2a147bc6d54adc0a3922e9a522cbb9410e8a85b3e8758a26ef1ac731
