apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/ecommerce-frontend
    newTag: "1.7.1"
    digest: sha256:3f9f45236bc6d3cce69cf31715441b17dc90133910ed5673962490aeb3529869
