apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-search-config
data:
  RUN_MODE: "prod"
  CONFIG_CENTER: "http://consul-server.consul.svc.cluster.local:8500"
  CONFIG_PATH: "ecommerce/search/prod.yml"
