// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	//GetOrderByNo
	//
	//  SELECT id, order_no, group_no, merchant_id, merchant_name, user_id, order_status, shipping_status, address_name, address_phone, address_province, address_city, address_district, address_detail, address_postal_code, address_full_text, total_amount, freight_amount, discount_amount, pay_amount, courier_code, courier_name, tracking_no, shipped_at, delivered_at, pay_channel, pay_no, paid_at, pay_deadline, remark, merchant_remark, created_at, updated_at
	//  FROM orders.order_main
	//  WHERE order_no = $1
	GetOrderByNo(ctx context.Context, orderNo string) (OrdersOrderMain, error)
}

var _ Querier = (*Queries)(nil)
