apiVersion: v1
kind: Service
metadata:
  name: ecommerce-order-service
  namespace: ecommerce
spec:
  externalTrafficPolicy: Local
  selector:
    app: ecommerce-order
  ports:
    - protocol: TCP
      port: 30004
      targetPort: 30004
  type: LoadBalancer
