# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/payment
    newTag: "1.7.4"
    digest: sha256:419229280b3f0facb946cfcf716ec697b873c39dc97a45759085af6a337500d1
