### healthz
POST http://{{host}}:{{port}}/healthz
Content-Type: application/json

### k8s
POST http://{{gateway_host}}:{{gateway_port}}/cart.v1.CartService/AddProductToCart
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "spuId": 5,
  "skuId": 9,
  "merchantId": "8966c1f2-fcc2-44bc-84f5-9de615ff235f",
  "quantity": 1,
  "selected": true,
  "spuName": "iphone-15-pro",
  "skuName": "iphone-15-pro-black-256g",
  "price": 22.20,
  "skuAttributes": {
    "a": "a",
    "b": 1
  },
  "skuThumbnailUrl": "https://cdn.example.com/iphone15pro/main.jpg",
  "status": "active"
}

### gateway RemoveCartItem
POST http://{{gateway_host}}:{{gateway_port}}/cart.v1.CartService/RemoveCartItem
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "spuId": 5,
  "skuId": 9,
  "merchantId": "eb70eac3-3b65-4a0a-a0e1-0d28fca13b82"
}

### RemoveCartItem
POST http://{{gateway_host}}:{{gateway_port}}/cart.v1.CartService/RemoveCartItem
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "spuId": 5,
  "skuId": 9,
  "merchantId": "eb70eac3-3b65-4a0a-a0e1-0d28fca13b82"
}

### GetCart
POST http://{{gateway_host}}:{{gateway_port}}/cart.v1.CartService/GetCart
Authorization: Bearer {{token}}
Content-Type: application/json

{}

### GetCart
POST http://{{host}}:{{port}}/cart.v1.CartService/GetCart
#Authorization: Bearer {{token}}
Content-Type: application/json

{}

###
