packages:
  - apps/*
  - packages/*
catalog:
  "@bufbuild/buf": latest
  "@bufbuild/protobuf": latest
  "@bufbuild/protoc-gen-es": latest
  "@connectrpc/connect": ^2.1.1
  "@connectrpc/connect-web": ^2.1.1
  "@emotion/react": latest
  "@emotion/styled": latest
  "@fontsource/roboto": latest
  "@mui/icons-material": latest
  "@mui/material": ^7.3.9
  "@mui/utils": latest
  "@t3-oss/env-core": ^0.13.10
  "@tanstack/react-devtools": latest
  "@tanstack/react-query": latest
  "@tanstack/react-query-devtools": latest
  "@tanstack/react-router": latest
  "@tanstack/react-router-devtools": latest
  "@tanstack/router-plugin": latest
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.1
  "@types/node": ^24
  "@types/react": latest
  "@types/react-dom": latest
  "@vitejs/plugin-react": ^6.0.1
  casdoor-js-sdk: ^0.18.0
  casdoor-react-sdk: latest
  conventional-changelog: latest
  jsdom: ^29.0.0
  lucide-react: latest
  react: latest
  react-dom: latest
  typescript: ^5
  valtio: latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.16
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  "vitest-browser-react": latest
  web-vitals: latest
  zod: ^4.3.6

catalogMode: prefer

onlyBuiltDependencies:
  - "@bufbuild/buf"
  - '@swc/core'
  - esbuild
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
