// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CartCartType string

const (
	CartCartTypeActive  CartCartType = "active"
	CartCartTypeExpired CartCartType = "expired"
	CartCartTypeDeleted CartCartType = "deleted"
)

func (e *CartCartType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CartCartType(s)
	case string:
		*e = CartCartType(s)
	default:
		return fmt.Errorf("unsupported scan type for CartCartType: %T", src)
	}
	return nil
}

type NullCartCartType struct {
	CartCartType CartCartType
	Valid        bool // Valid is true if CartCartType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCartCartType) Scan(value interface{}) error {
	if value == nil {
		ns.CartCartType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CartCartType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCartCartType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CartCartType), nil
}

func (e CartCartType) Valid() bool {
	switch e {
	case CartCartTypeActive,
		CartCartTypeExpired,
		CartCartTypeDeleted:
		return true
	}
	return false
}

func AllCartCartTypeValues() []CartCartType {
	return []CartCartType{
		CartCartTypeActive,
		CartCartTypeExpired,
		CartCartTypeDeleted,
	}
}

// 购物车明细表
type CartCartItem struct {
	ID              int64
	UserID          uuid.UUID
	MerchantID      uuid.UUID
	SpuID           int64
	SkuID           int64
	Quantity        int32
	Selected        bool
	SpuName         string
	SkuName         string
	Price           pgtype.Numeric
	SkuAttributes   []byte
	SkuThumbnailUrl string
	Status          interface{}
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
