// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	//AddProductToCart
	//
	//  WITH upsert AS (
	//      INSERT INTO cart.cart_item (user_id,
	//                                  merchant_id,
	//                                  spu_id,
	//                                  sku_id,
	//                                  quantity,
	//                                  selected,
	//                                  spu_name,
	//                                  sku_name,
	//                                  price,
	//                                  sku_attributes,
	//                                  sku_thumbnail_url,
	//                                  status)
	//          VALUES ($1,
	//                  $2,
	//                  $3,
	//                  $4,
	//                  $5,
	//                  $6,
	//                  $7,
	//                  $8,
	//                  $9,
	//                  $10,
	//                  $11,
	//                  $12)
	//          ON CONFLICT (user_id, merchant_id, sku_id)
	//              DO UPDATE SET
	//                  -- 用户重新加这个商品时，默认帮他重新勾选上
	//                  selected = EXCLUDED.selected,
	//                  -- 状态重新校准为正常
	//                  status = EXCLUDED.status,
	//                  updated_at = now()
	//          -- 返回新增/更新命中的购物车项ID（前端下单需要真实ID）
	//          RETURNING id)
	//  SELECT upsert.id                                                      AS cart_item_id,
	//         (SELECT COUNT(*) FROM cart.cart_item WHERE user_id = $1) AS cart_item_quantity
	//  FROM upsert
	AddProductToCart(ctx context.Context, arg AddProductToCartParams) (AddProductToCartRow, error)
	// 获取用户购物车所有商品
	//
	//  SELECT id,
	//         merchant_id,
	//         shop_name,
	//         spu_id,
	//         sku_id,
	//         quantity,
	//         selected,
	//         spu_name,
	//         sku_name,
	//         price,
	//         sku_attributes,
	//         sku_thumbnail_url,
	//         status,
	//         created_at,
	//         updated_at
	//  FROM cart.cart_item
	//  WHERE user_id = $1
	//    AND status = $2
	//  ORDER BY updated_at DESC
	GetCartItems(ctx context.Context, arg GetCartItemsParams) ([]GetCartItemsRow, error)
	// 删除购物车项, 返回删除后的购物车总商品项和是否为空购物车和删除的购物车商品数量
	//
	//  WITH deleted AS (
	//      DELETE
	//          FROM cart.cart_item
	//              WHERE user_id = $1
	//                  AND (merchant_id, spu_id, sku_id, status) IN
	//                      (SELECT unnest($2::uuid[]),
	//                              unnest($3::bigint[]),
	//                              unnest($4::bigint[]),
	//                              unnest($5::cart.cart_type[]))
	//              RETURNING id),
	//       remaining AS (SELECT COUNT(*) AS cnt
	//                     FROM cart.cart_item
	//                     WHERE user_id = $1
	//                       AND status = $6)
	//  SELECT (SELECT cnt FROM remaining)     AS cart_item_quantity,
	//         (SELECT cnt FROM remaining) = 0 AS is_cart_empty,
	//         (SELECT COUNT(*) FROM deleted)  AS deleted_count
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) (RemoveCartItemRow, error)
	// 更新商品数量, 并返回购物车商品总数量
	//
	//  WITH do_uodate AS (
	//      UPDATE cart.cart_item
	//          SET quantity = $3,
	//              updated_at = now()
	//          WHERE merchant_id = $4
	//              AND user_id = $1
	//              AND spu_id = $5
	//              AND sku_id = $6
	//              AND status = $2
	//              AND $3 > 0)
	//  SELECT COUNT(*) AS cart_total_quantity
	//  FROM cart.cart_item
	//  WHERE user_id = $1
	//    AND status = $2
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
