// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	//AddProductToCart
	//
	//  INSERT INTO cart.cart_item(user_id,
	//                             merchant_id,
	//                             spu_id,
	//                             sku_id,
	//                             quantity,
	//                             selected,
	//                             spu_name,
	//                             sku_name,
	//                             price,
	//                             sku_attributes,
	//                             sku_thumbnail_url,
	//                             status)
	//  VALUES ($1,
	//          $2,
	//          $3,
	//          $4,
	//          $5,
	//          $6,
	//          $7,
	//          $8,
	//          $9,
	//          $10,
	//          $11,
	//          $12)
	//  ON CONFLICT (user_id, merchant_id, sku_id)
	//      DO UPDATE SET
	//                    -- 如果商品已存在，数量进行累加 (旧数量 + 新传入的数量)
	//                    quantity   = cart_item.quantity + EXCLUDED.quantity,
	//                    -- 用户重新加这个商品时，默认帮他重新勾选上
	//                    selected   = EXCLUDED.selected,
	//                    -- 状态重新校准为正常
	//                    status     = EXCLUDED.status,
	//                    updated_at = now()
	//  RETURNING id, quantity
	AddProductToCart(ctx context.Context, arg AddProductToCartParams) (AddProductToCartRow, error)
	// 获取用户购物车所有商品
	//
	//  SELECT id,
	//         merchant_id,
	//         spu_id,
	//         sku_id,
	//         quantity,
	//         selected,
	//         spu_name,
	//         sku_name,
	//         price,
	//         sku_attributes,
	//         sku_thumbnail_url,
	//         status,
	//         created_at,
	//         updated_at
	//  FROM cart.cart_item
	//  WHERE user_id = $1
	//    AND status = $2
	//  ORDER BY updated_at DESC
	GetCartItems(ctx context.Context, arg GetCartItemsParams) ([]GetCartItemsRow, error)
	// 把最新的 id 和叠加后的最终数量一起返回回去
	//
	//
	//  WITH deleted AS (
	//      DELETE FROM cart.cart_item
	//          WHERE merchant_id = $3
	//              AND user_id = $1
	//              AND spu_id = $4
	//              AND sku_id = $5
	//              AND status = $2
	//          RETURNING id)
	//  SELECT COALESCE(COUNT(quantity), 0)::INT AS cart_total_quantity,
	//         CASE
	//             WHEN COUNT(*) = 0 THEN
	//                 TRUE
	//             ELSE
	//                 FALSE
	//             END                           AS is_cart_empty
	//  FROM cart.cart_item
	//  WHERE user_id = $1
	//    AND status = $2
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) (RemoveCartItemRow, error)
	// 更新商品数量, 并返回购物车商品总数量
	//
	//  WITH do_uodate AS (
	//      UPDATE cart.cart_item
	//          SET quantity = $3,
	//              updated_at = now()
	//          WHERE merchant_id = $4
	//              AND user_id = $1
	//              AND spu_id = $5
	//              AND sku_id = $6
	//              AND status = $2
	//              AND $3 > 0)
	//  SELECT COUNT(*) AS cart_total_quantity
	//  FROM cart.cart_item
	//  WHERE user_id = $1
	//    AND status = $2
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
