apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecommerce-services
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@gitlab.com:sumery/ecommerce.git   # 你的 GitLab 地址
        revision: main
        directories:
          - path: helm/charts/*          # 扫描 helm/charts/ 下的所有子目录
  template:
    metadata:
      name: '{{.path.basename}}'    # 应用名取子目录名，如 address, cart
    spec:
      project: ecommerce
      source:
        repoURL: git@gitlab.com:sumery/ecommerce.git
        path: '{{.path.path}}'      # 指向 helm/charts/<service>
        targetRevision: main
        helm:
#          # 方法一：使用 values 文件（推荐）
#          valueFiles:
#            - values.yaml              # 默认 values（每个 Chart 内必须有）
#            - envs/{{.path.basename}}/values.yaml  # 可选：环境特定值（需提前创建）
#          # 方法二：使用 set 参数（覆盖个别值）
          parameters:
            - name: image.tag
              value: "0.1.0"           # 可通过 CI 动态替换
      destination:
        server: https://kubernetes.default.svc
        namespace: ecommerce
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
