# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/search
    newTag: "1.7.1"
    digest: sha256:a4b5a770c7d1348353bf49ff8bf894926a7a95d1882dcdcf8bd09e439bc70887
