services:

  user:
    image: harbor.apikv.com:5443/sumery/ecommerce/user:dev
    environment:
      HTTP_ADDR: 0.0.0.0:4000
      RUN_MODE: prod
    ports:
      - "0.0.0.0:4000:4000"
    container_name: user
    restart: on-failure:3
#    environment:
#      - DISCOVERY_DSN=consul://apikv.com:8500
#      - DISCOVERY_CONFIG_PATH=ecommerce/gateway/config.yaml
#    volumes:
#      # 仅挂载本地配置文件（开发环境）
#      - ./dynamic-config:/app/dynamic-config
#    command: [ "/app/gateway" ]
#    networks:
#      - ecommerce
