// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Stockstatus string

const (
	StockstatusAvailable Stockstatus = "available"
	StockstatusReserved  Stockstatus = "reserved"
	StockstatusLocked    Stockstatus = "locked"
	StockstatusDeducted  Stockstatus = "deducted"
	StockstatusReleased  Stockstatus = "released"
)

func (e *Stockstatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Stockstatus(s)
	case string:
		*e = Stockstatus(s)
	default:
		return fmt.Errorf("unsupported scan type for Stockstatus: %T", src)
	}
	return nil
}

type NullStockstatus struct {
	Stockstatus Stockstatus
	Valid       bool // Valid is true if Stockstatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockstatus) Scan(value interface{}) error {
	if value == nil {
		ns.Stockstatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Stockstatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockstatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Stockstatus), nil
}

func (e Stockstatus) Valid() bool {
	switch e {
	case StockstatusAvailable,
		StockstatusReserved,
		StockstatusLocked,
		StockstatusDeducted,
		StockstatusReleased:
		return true
	}
	return false
}

func AllStockstatusValues() []Stockstatus {
	return []Stockstatus{
		StockstatusAvailable,
		StockstatusReserved,
		StockstatusLocked,
		StockstatusDeducted,
		StockstatusReleased,
	}
}

type InventoryChangeLog struct {
	ID              int64
	OrderNo         string
	SkuID           int64
	WarehouseID     string
	MerchantID      uuid.UUID
	ChangeType      string
	FromStatus      *Stockstatus
	ToStatus        Stockstatus
	Quantity        int32
	BeforeOnHand    int32
	AfterOnHand     int32
	BeforeLocked    int32
	AfterLocked     int32
	BeforeAvailable int32
	AfterAvailable  int32
	Operator        *string
	Remark          *string
	CreatedAt       time.Time
}

type InventoryStock struct {
	ID          int64
	SkuID       int64
	WarehouseID string
	MerchantID  uuid.UUID
	OnHand      int32
	Locked      int32
	Available   int32
	Version     int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
