---
{
  apiVersion: "networking.k8s.io/v1",
  kind: "NetworkPolicy",
  metadata: {
    name: "ecommerce-db-migrate",
    namespace: {{ .Release.Namespace | quote }},
    annotations: {
      argocd.argoproj.io/hook: "PreSync",
      argocd.argoproj.io/sync-wave: "-2",
      argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation",
      helm.sh/hook: "pre-install,pre-upgrade",
      helm.sh/hook-weight: "-2",
      helm.sh/hook-delete-policy: "before-hook-creation",
    },
  },
  spec: {
    podSelector: { matchLabels: { app.kubernetes.io/name: "ecommerce-db-migrate" } },
    policyTypes: ["Ingress", "Egress"],
    ingress: [],
    egress: [{
      to: [{
        namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: "kube-system" } },
        podSelector: { matchLabels: { k8s-app: "kube-dns" } },
      }],
      ports: [{ protocol: "UDP", port: 53 }, { protocol: "TCP", port: 53 }],
    }, {
      to: [{
        namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: "postgresql" } },
        podSelector: { matchLabels: { cnpg.io/cluster: "pg-main" } },
      }],
      ports: [{ protocol: "TCP", port: 5432 }],
    }],
  },
}
