enabled: true
replicaCount: 1
image:
  repository: ccr.ccs.tencentyun.com/sumery/user
  tag: dev
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 30001
  targetPort: 30001
environment:
  CONSUL_ENABLED: true
  CONSUL_ADDR: consul.sumery.com
  CONSUL_PATH: ecommerce/user/dev.yml
  CONSUL_SCHEME: https
  CONSUL_INSECURE_SKIP_VERIFY: true
autoscaling:
  enabled: false
