// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package models

import (
	"context"
	"time"
)

const DeleteEntry = `-- name: DeleteEntry :execrows
DELETE FROM config.entry
WHERE namespace = $1
  AND environment = $2
  AND key = $3
`

type DeleteEntryParams struct {
	Namespace   string
	Environment string
	Key         string
}

// DeleteEntry
//
//	DELETE FROM config.entry
//	WHERE namespace = $1
//	  AND environment = $2
//	  AND key = $3
func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteEntry, arg.Namespace, arg.Environment, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetEntry = `-- name: GetEntry :one
SELECT id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
FROM config.entry
WHERE namespace = $1
  AND environment = $2
  AND key = $3
`

type GetEntryParams struct {
	Namespace   string
	Environment string
	Key         string
}

// GetEntry
//
//	SELECT id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
//	FROM config.entry
//	WHERE namespace = $1
//	  AND environment = $2
//	  AND key = $3
func (q *Queries) GetEntry(ctx context.Context, arg GetEntryParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, GetEntry, arg.Namespace, arg.Environment, arg.Key)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Environment,
		&i.Key,
		&i.Format,
		&i.Value,
		&i.Version,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetEntryForUpdate = `-- name: GetEntryForUpdate :one
SELECT id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
FROM config.entry
WHERE namespace = $1
  AND environment = $2
  AND key = $3
FOR UPDATE
`

type GetEntryForUpdateParams struct {
	Namespace   string
	Environment string
	Key         string
}

// GetEntryForUpdate
//
//	SELECT id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
//	FROM config.entry
//	WHERE namespace = $1
//	  AND environment = $2
//	  AND key = $3
//	FOR UPDATE
func (q *Queries) GetEntryForUpdate(ctx context.Context, arg GetEntryForUpdateParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, GetEntryForUpdate, arg.Namespace, arg.Environment, arg.Key)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Environment,
		&i.Key,
		&i.Format,
		&i.Value,
		&i.Version,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetRevisionByVersion = `-- name: GetRevisionByVersion :one
SELECT id, entry_id, version, format, value, comment, author, created_at
FROM config.revision
WHERE entry_id = $1
  AND version = $2
`

type GetRevisionByVersionParams struct {
	EntryID int64
	Version int32
}

// GetRevisionByVersion
//
//	SELECT id, entry_id, version, format, value, comment, author, created_at
//	FROM config.revision
//	WHERE entry_id = $1
//	  AND version = $2
func (q *Queries) GetRevisionByVersion(ctx context.Context, arg GetRevisionByVersionParams) (ConfigRevision, error) {
	row := q.db.QueryRow(ctx, GetRevisionByVersion, arg.EntryID, arg.Version)
	var i ConfigRevision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Version,
		&i.Format,
		&i.Value,
		&i.Comment,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const InsertEntry = `-- name: InsertEntry :one
INSERT INTO config.entry (namespace, environment, key, format, value, version, is_secret, description, updated_by)
VALUES ($1, $2, $3, $4, $5, 1, $6, $7, $8)
RETURNING id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
`

type InsertEntryParams struct {
	Namespace   string
	Environment string
	Key         string
	Format      string
	Value       string
	IsSecret    bool
	Description string
	UpdatedBy   string
}

// InsertEntry
//
//	INSERT INTO config.entry (namespace, environment, key, format, value, version, is_secret, description, updated_by)
//	VALUES ($1, $2, $3, $4, $5, 1, $6, $7, $8)
//	RETURNING id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, InsertEntry,
		arg.Namespace,
		arg.Environment,
		arg.Key,
		arg.Format,
		arg.Value,
		arg.IsSecret,
		arg.Description,
		arg.UpdatedBy,
	)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Environment,
		&i.Key,
		&i.Format,
		&i.Value,
		&i.Version,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const InsertRevision = `-- name: InsertRevision :one
INSERT INTO config.revision (entry_id, version, format, value, comment, author)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entry_id, version, format, value, comment, author, created_at
`

type InsertRevisionParams struct {
	EntryID int64
	Version int32
	Format  string
	Value   string
	Comment string
	Author  string
}

// InsertRevision
//
//	INSERT INTO config.revision (entry_id, version, format, value, comment, author)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id, entry_id, version, format, value, comment, author, created_at
func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) (ConfigRevision, error) {
	row := q.db.QueryRow(ctx, InsertRevision,
		arg.EntryID,
		arg.Version,
		arg.Format,
		arg.Value,
		arg.Comment,
		arg.Author,
	)
	var i ConfigRevision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Version,
		&i.Format,
		&i.Value,
		&i.Comment,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const ListEntries = `-- name: ListEntries :many
SELECT id, namespace, environment, key, format, version, is_secret, description, updated_by, created_at, updated_at
FROM config.entry
WHERE namespace = $1
  AND environment = $2
  AND key LIKE $3 || '%'
ORDER BY key
`

type ListEntriesParams struct {
	Namespace   string
	Environment string
	KeyPrefix   *string
}

type ListEntriesRow struct {
	ID          int64
	Namespace   string
	Environment string
	Key         string
	Format      string
	Version     int32
	IsSecret    bool
	Description string
	UpdatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// ListEntries
//
//	SELECT id, namespace, environment, key, format, version, is_secret, description, updated_by, created_at, updated_at
//	FROM config.entry
//	WHERE namespace = $1
//	  AND environment = $2
//	  AND key LIKE $3 || '%'
//	ORDER BY key
func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, ListEntries, arg.Namespace, arg.Environment, arg.KeyPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Namespace,
			&i.Environment,
			&i.Key,
			&i.Format,
			&i.Version,
			&i.IsSecret,
			&i.Description,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListNamespaceEnvironments = `-- name: ListNamespaceEnvironments :many
SELECT namespace, environment, COUNT(*)::int AS key_count
FROM config.entry
GROUP BY namespace, environment
ORDER BY namespace, environment
`

type ListNamespaceEnvironmentsRow struct {
	Namespace   string
	Environment string
	KeyCount    int32
}

// 走 idx_entry_ns_env 索引扫描,返回 (namespace, environment) 维度的 key 数量。
//
//	SELECT namespace, environment, COUNT(*)::int AS key_count
//	FROM config.entry
//	GROUP BY namespace, environment
//	ORDER BY namespace, environment
func (q *Queries) ListNamespaceEnvironments(ctx context.Context) ([]ListNamespaceEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, ListNamespaceEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamespaceEnvironmentsRow
	for rows.Next() {
		var i ListNamespaceEnvironmentsRow
		if err := rows.Scan(&i.Namespace, &i.Environment, &i.KeyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRevisions = `-- name: ListRevisions :many
SELECT id, entry_id, version, format, value, comment, author, created_at
FROM config.revision
WHERE entry_id = $1
ORDER BY version DESC
`

// ListRevisions
//
//	SELECT id, entry_id, version, format, value, comment, author, created_at
//	FROM config.revision
//	WHERE entry_id = $1
//	ORDER BY version DESC
func (q *Queries) ListRevisions(ctx context.Context, entryID int64) ([]ConfigRevision, error) {
	rows, err := q.db.Query(ctx, ListRevisions, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigRevision
	for rows.Next() {
		var i ConfigRevision
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Version,
			&i.Format,
			&i.Value,
			&i.Comment,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateEntry = `-- name: UpdateEntry :one
UPDATE config.entry
SET value       = $1,
    format      = $2,
    version     = $3,
    is_secret   = $4,
    description = $5,
    updated_by  = $6,
    updated_at  = now()
WHERE id = $7
RETURNING id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
`

type UpdateEntryParams struct {
	Value       string
	Format      string
	Version     int32
	IsSecret    bool
	Description string
	UpdatedBy   string
	ID          int64
}

// UpdateEntry
//
//	UPDATE config.entry
//	SET value       = $1,
//	    format      = $2,
//	    version     = $3,
//	    is_secret   = $4,
//	    description = $5,
//	    updated_by  = $6,
//	    updated_at  = now()
//	WHERE id = $7
//	RETURNING id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, UpdateEntry,
		arg.Value,
		arg.Format,
		arg.Version,
		arg.IsSecret,
		arg.Description,
		arg.UpdatedBy,
		arg.ID,
	)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Namespace,
		&i.Environment,
		&i.Key,
		&i.Format,
		&i.Value,
		&i.Version,
		&i.IsSecret,
		&i.Description,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
