// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"
)

type ConfigEntry struct {
	ID          int64
	Namespace   string
	Environment string
	Key         string
	Format      string
	Value       string
	Version     int32
	IsSecret    bool
	Description string
	UpdatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ConfigRevision struct {
	ID        int64
	EntryID   int64
	Version   int32
	Format    string
	Value     string
	Comment   string
	Author    string
	CreatedAt time.Time
}
