// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	//DeleteEntry
	//
	//  DELETE FROM config.entry
	//  WHERE namespace = $1
	//    AND environment = $2
	//    AND key = $3
	DeleteEntry(ctx context.Context, arg DeleteEntryParams) (int64, error)
	//GetEntry
	//
	//  SELECT id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
	//  FROM config.entry
	//  WHERE namespace = $1
	//    AND environment = $2
	//    AND key = $3
	GetEntry(ctx context.Context, arg GetEntryParams) (ConfigEntry, error)
	//GetEntryForUpdate
	//
	//  SELECT id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
	//  FROM config.entry
	//  WHERE namespace = $1
	//    AND environment = $2
	//    AND key = $3
	//  FOR UPDATE
	GetEntryForUpdate(ctx context.Context, arg GetEntryForUpdateParams) (ConfigEntry, error)
	//GetRevisionByVersion
	//
	//  SELECT id, entry_id, version, format, value, comment, author, created_at
	//  FROM config.revision
	//  WHERE entry_id = $1
	//    AND version = $2
	GetRevisionByVersion(ctx context.Context, arg GetRevisionByVersionParams) (ConfigRevision, error)
	//InsertEntry
	//
	//  INSERT INTO config.entry (namespace, environment, key, format, value, version, is_secret, description, updated_by)
	//  VALUES ($1, $2, $3, $4, $5, 1, $6, $7, $8)
	//  RETURNING id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
	InsertEntry(ctx context.Context, arg InsertEntryParams) (ConfigEntry, error)
	//InsertRevision
	//
	//  INSERT INTO config.revision (entry_id, version, format, value, comment, author)
	//  VALUES ($1, $2, $3, $4, $5, $6)
	//  RETURNING id, entry_id, version, format, value, comment, author, created_at
	InsertRevision(ctx context.Context, arg InsertRevisionParams) (ConfigRevision, error)
	//ListEntries
	//
	//  SELECT id, namespace, environment, key, format, version, is_secret, description, updated_by, created_at, updated_at
	//  FROM config.entry
	//  WHERE namespace = $1
	//    AND environment = $2
	//    AND key LIKE $3 || '%'
	//  ORDER BY key
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]ListEntriesRow, error)
	// 走 idx_entry_ns_env 索引扫描,返回 (namespace, environment) 维度的 key 数量。
	//
	//  SELECT namespace, environment, COUNT(*)::int AS key_count
	//  FROM config.entry
	//  GROUP BY namespace, environment
	//  ORDER BY namespace, environment
	ListNamespaceEnvironments(ctx context.Context) ([]ListNamespaceEnvironmentsRow, error)
	//ListRevisions
	//
	//  SELECT id, entry_id, version, format, value, comment, author, created_at
	//  FROM config.revision
	//  WHERE entry_id = $1
	//  ORDER BY version DESC
	ListRevisions(ctx context.Context, entryID int64) ([]ConfigRevision, error)
	//UpdateEntry
	//
	//  UPDATE config.entry
	//  SET value       = $1,
	//      format      = $2,
	//      version     = $3,
	//      is_secret   = $4,
	//      description = $5,
	//      updated_by  = $6,
	//      updated_at  = now()
	//  WHERE id = $7
	//  RETURNING id, namespace, environment, key, format, value, version, is_secret, description, updated_by, created_at, updated_at
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (ConfigEntry, error)
}

var _ Querier = (*Queries)(nil)
