// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file api/search/v1/search.proto (package search.v1, syntax proto3)
/* eslint-disable */

// 独立搜索功能

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_third_party_validate_validate } from "../../../third_party/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/search/v1/search.proto.
 */
export const file_api_search_v1_search: GenFile = /*@__PURE__*/
  fileDesc("ChphcGkvc2VhcmNoL3YxL3NlYXJjaC5wcm90bxIJc2VhcmNoLnYxIlwKDVNlYXJjaFJlcXVlc3QSMQoFaW5kZXgYASABKAlCIrpIH3IdEAEY/wEyFl5bYS16MC05XVthLXowLTkuXy1dKiQSGAoEbmFtZRgCIAEoCUIKukgHcgUQARiAASJACg5TZWFyY2hSZXNwb25zZRIuCghwcm9kdWN0cxgBIAMoCzISLnNlYXJjaC52MS5Qcm9kdWN0Qgi6SAWSAQIQZCLtAQoHUHJvZHVjdBITCgJpZBgBIAEoDUIHukgEKgIgABIbCghzcHVfY29kZRgCIAEoCUIJukgGcgQQARhAEigKBXByaWNlGAMgASgBQhm6SBYSFEABGY/C9f+D15dBKQAAAAAAAAAAEjYKBnN0YXR1cxgEIAEoCUImukgjciFSBWRyYWZ0UgZvbmxpbmVSB29mZmxpbmVSB2RlbGV0ZWQSIgoObWFpbl9tZWRpYV91cmwYBSABKAlCCrpIB3IFEAEY9AMSEAoIcXVhbnRpdHkYBiABKA0SGAoEbmFtZRgHIAEoCUIKukgHcgUQARj/ATJQCg1TZWFyY2hTZXJ2aWNlEj8KBlNlYXJjaBIYLnNlYXJjaC52MS5TZWFyY2hSZXF1ZXN0Ghkuc2VhcmNoLnYxLlNlYXJjaFJlc3BvbnNlIgBCPVo7Z2l0aHViLmNvbS9sZW5zMDc3L2Vjb21tZXJjZS9iYWNrZW5kL2FwaS9zZWFyY2gvdjE7c2VhcmNodjFiBnByb3RvMw", [file_third_party_validate_validate]);

/**
 * @generated from message search.v1.SearchRequest
 */
export type SearchRequest = Message<"search.v1.SearchRequest"> & {
  /**
   * @generated from field: string index = 1;
   */
  index: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message search.v1.SearchRequest.
 * Use `create(SearchRequestSchema)` to create a new message.
 */
export const SearchRequestSchema: GenMessage<SearchRequest> = /*@__PURE__*/
  messageDesc(file_api_search_v1_search, 0);

/**
 * @generated from message search.v1.SearchResponse
 */
export type SearchResponse = Message<"search.v1.SearchResponse"> & {
  /**
   * @generated from field: repeated search.v1.Product products = 1;
   */
  products: Product[];
};

/**
 * Describes the message search.v1.SearchResponse.
 * Use `create(SearchResponseSchema)` to create a new message.
 */
export const SearchResponseSchema: GenMessage<SearchResponse> = /*@__PURE__*/
  messageDesc(file_api_search_v1_search, 1);

/**
 * 定义 Product 消息 (对应 Go 结构体中的 Product)
 *
 * @generated from message search.v1.Product
 */
export type Product = Message<"search.v1.Product"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string spu_code = 2;
   */
  spuCode: string;

  /**
   * @generated from field: double price = 3;
   */
  price: number;

  /**
   * @generated from field: string status = 4;
   */
  status: string;

  /**
   * @generated from field: string main_media_url = 5;
   */
  mainMediaUrl: string;

  /**
   * @generated from field: uint32 quantity = 6;
   */
  quantity: number;

  /**
   * @generated from field: string name = 7;
   */
  name: string;
};

/**
 * Describes the message search.v1.Product.
 * Use `create(ProductSchema)` to create a new message.
 */
export const ProductSchema: GenMessage<Product> = /*@__PURE__*/
  messageDesc(file_api_search_v1_search, 2);

/**
 * @generated from service search.v1.SearchService
 */
export const SearchService: GenService<{
  /**
   * @generated from rpc search.v1.SearchService.Search
   */
  search: {
    methodKind: "unary";
    input: typeof SearchRequestSchema;
    output: typeof SearchResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_search_v1_search, 0);

