enabled: true
replicaCount: 1
image:
  repository: "harbor.apikv.com:5443/sumery/connect-example-frontend"
  tag: "1.4.1"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 3000
  targetPort: 80
autoscaling:
  enabled: false
