replicaCount: 1
enabled: true

image:
  repository: "sumery/inventory"
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    http:
      enabled: true
      port: 30007
      targetPort: 30007
    grpc:
      enabled: false
      port: 30008
      targetPort: 30008

env:
  - name: DB_SOURCE
    valueFrom:
      secretKeyRef:
        name: ecommerce-db-secret
        key: DB_SOURCE

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

secret:
  enabled: true
  name: "ecommerce-db-secret"
  data:
    DB_SOURCE: ""