apiVersion: v1
kind: Service
metadata:
  name: ecommerce-inventory-service
spec:
  selector:
    app: ecommerce-inventory
  ports:
    - protocol: TCP
      port: 30005
      targetPort: 30005
  type: LoadBalancer
