// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/inventory/v1/inventory.proto (package inventory.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_third_party_validate_validate } from "../../../third_party/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/inventory/v1/inventory.proto.
 */
export const file_api_inventory_v1_inventory: GenFile = /*@__PURE__*/
  fileDesc("CiBhcGkvaW52ZW50b3J5L3YxL2ludmVudG9yeS5wcm90bxIMaW52ZW50b3J5LnYxImsKDlJlc2VydmVSZXF1ZXN0EhAKCG9yZGVyX25vGAEgASgJEh0KC21lcmNoYW50X2lkGAIgASgJQgi6SAVyA7ABARIoCgVpdGVtcxgDIAMoCzIZLmludmVudG9yeS52MS5SZXNlcnZlSXRlbSJbCgtSZXNlcnZlSXRlbRIOCgZza3VfaWQYASABKAMSHAoIcXVhbnRpdHkYAiABKAVCCrpIBxoFGOcHIAASHgoLd2FyZWhvdXNlSWQYAyABKAlCCbpIBnIEEAYYBiIuCg9SZXNlcnZlUmVzcG9uc2USDgoGc3RhdHVzGAEgASgIEgsKA21zZxgCIAEoCSJyChVSZWxlYXNlUmVzZXJ2ZVJlcXVlc3QSEAoIb3JkZXJfbm8YASABKAkSHQoLbWVyY2hhbnRfaWQYAiABKAlCCLpIBXIDsAEBEigKBWl0ZW1zGAMgAygLMhkuaW52ZW50b3J5LnYxLlJlc2VydmVJdGVtIjUKFlJlbGVhc2VSZXNlcnZlUmVzcG9uc2USDgoGc3RhdHVzGAEgASgIEgsKA21zZxgCIAEoCTK7AQoQSW52ZW50b3J5U2VydmljZRJICgdSZXNlcnZlEhwuaW52ZW50b3J5LnYxLlJlc2VydmVSZXF1ZXN0Gh0uaW52ZW50b3J5LnYxLlJlc2VydmVSZXNwb25zZSIAEl0KDlJlbGVhc2VSZXNlcnZlEiMuaW52ZW50b3J5LnYxLlJlbGVhc2VSZXNlcnZlUmVxdWVzdBokLmludmVudG9yeS52MS5SZWxlYXNlUmVzZXJ2ZVJlc3BvbnNlIgBCtgEKEGNvbS5pbnZlbnRvcnkudjFCDkludmVudG9yeVByb3RvUAFaQWdpdGh1Yi5jb20vbGVuczA3Ny9lY29tbWVyY2UvYmFja2VuZC9hcGkvaW52ZW50b3J5L3YxO2ludmVudG9yeXYxogIDSVhYqgIMSW52ZW50b3J5LlYxygIMSW52ZW50b3J5XFYx4gIYSW52ZW50b3J5XFYxXEdQQk1ldGFkYXRh6gINSW52ZW50b3J5OjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp, file_third_party_validate_validate]);

/**
 * @generated from message inventory.v1.ReserveRequest
 */
export type ReserveRequest = Message<"inventory.v1.ReserveRequest"> & {
  /**
   * 订单号，用于幂等去重
   *
   * @generated from field: string order_no = 1;
   */
  orderNo: string;

  /**
   * 商家ID（数据隔离）
   *
   * @generated from field: string merchant_id = 2;
   */
  merchantId: string;

  /**
   * 需要预占的商品列表
   *
   * @generated from field: repeated inventory.v1.ReserveItem items = 3;
   */
  items: ReserveItem[];
};

/**
 * Describes the message inventory.v1.ReserveRequest.
 * Use `create(ReserveRequestSchema)` to create a new message.
 */
export const ReserveRequestSchema: GenMessage<ReserveRequest> = /*@__PURE__*/
  messageDesc(file_api_inventory_v1_inventory, 0);

/**
 * @generated from message inventory.v1.ReserveItem
 */
export type ReserveItem = Message<"inventory.v1.ReserveItem"> & {
  /**
   * 商品SKU ID
   *
   * @generated from field: int64 sku_id = 1;
   */
  skuId: bigint;

  /**
   * @generated from field: int32 quantity = 2;
   */
  quantity: number;

  /**
   * @generated from field: string warehouseId = 3;
   */
  warehouseId: string;
};

/**
 * Describes the message inventory.v1.ReserveItem.
 * Use `create(ReserveItemSchema)` to create a new message.
 */
export const ReserveItemSchema: GenMessage<ReserveItem> = /*@__PURE__*/
  messageDesc(file_api_inventory_v1_inventory, 1);

/**
 * @generated from message inventory.v1.ReserveResponse
 */
export type ReserveResponse = Message<"inventory.v1.ReserveResponse"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;

  /**
   * @generated from field: string msg = 2;
   */
  msg: string;
};

/**
 * Describes the message inventory.v1.ReserveResponse.
 * Use `create(ReserveResponseSchema)` to create a new message.
 */
export const ReserveResponseSchema: GenMessage<ReserveResponse> = /*@__PURE__*/
  messageDesc(file_api_inventory_v1_inventory, 2);

/**
 * @generated from message inventory.v1.ReleaseReserveRequest
 */
export type ReleaseReserveRequest = Message<"inventory.v1.ReleaseReserveRequest"> & {
  /**
   * 订单号，用于幂等去重
   *
   * @generated from field: string order_no = 1;
   */
  orderNo: string;

  /**
   * 商家ID（数据隔离）
   *
   * @generated from field: string merchant_id = 2;
   */
  merchantId: string;

  /**
   * 需要释放预占的商品列表
   *
   * @generated from field: repeated inventory.v1.ReserveItem items = 3;
   */
  items: ReserveItem[];
};

/**
 * Describes the message inventory.v1.ReleaseReserveRequest.
 * Use `create(ReleaseReserveRequestSchema)` to create a new message.
 */
export const ReleaseReserveRequestSchema: GenMessage<ReleaseReserveRequest> = /*@__PURE__*/
  messageDesc(file_api_inventory_v1_inventory, 3);

/**
 * @generated from message inventory.v1.ReleaseReserveResponse
 */
export type ReleaseReserveResponse = Message<"inventory.v1.ReleaseReserveResponse"> & {
  /**
   * @generated from field: bool status = 1;
   */
  status: boolean;

  /**
   * @generated from field: string msg = 2;
   */
  msg: string;
};

/**
 * Describes the message inventory.v1.ReleaseReserveResponse.
 * Use `create(ReleaseReserveResponseSchema)` to create a new message.
 */
export const ReleaseReserveResponseSchema: GenMessage<ReleaseReserveResponse> = /*@__PURE__*/
  messageDesc(file_api_inventory_v1_inventory, 4);

/**
 * @generated from service inventory.v1.InventoryService
 */
export const InventoryService: GenService<{
  /**
   * 预占库存(下单但未支付): 可用 -> 预占
   *
   * @generated from rpc inventory.v1.InventoryService.Reserve
   */
  reserve: {
    methodKind: "unary";
    input: typeof ReserveRequestSchema;
    output: typeof ReserveResponseSchema;
  },
  /**
   * 释放预占库存(未支付取消/超时取消): 预占 -> 可用
   *
   * @generated from rpc inventory.v1.InventoryService.ReleaseReserve
   */
  releaseReserve: {
    methodKind: "unary";
    input: typeof ReleaseReserveRequestSchema;
    output: typeof ReleaseReserveResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_inventory_v1_inventory, 0);

