services:
  frontend:
    image: harbor.apikv.com:5443/ecommerce/frontend:latest
    container_name: ecommerce-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
      target: final
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    # 环境变量
    environment:
      - GATEWAY_URL=http://localhost:8080 # 生产环境的网关地址
    restart: on-failure:4 # 重启策略，最多重启n次
