// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/cart/v1/cart.proto

package cartv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProductToCartRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SpuId      uint64                 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuId      uint64                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	MerchantId string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Quantity   uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Selected   bool                   `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"` // 同步勾选状态, 多端同步
	// 商品快照, 避免商家修改商品
	SpuName         string           `protobuf:"bytes,6,opt,name=spu_name,json=spuName,proto3" json:"spu_name,omitempty"`
	SkuName         string           `protobuf:"bytes,7,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Price           float64          `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	SkuAttributes   *structpb.Struct `protobuf:"bytes,9,opt,name=sku_attributes,json=skuAttributes,proto3" json:"sku_attributes,omitempty"`
	SkuThumbnailUrl string           `protobuf:"bytes,10,opt,name=sku_thumbnail_url,json=skuThumbnailUrl,proto3" json:"sku_thumbnail_url,omitempty"` // 商品图片
	Status          string           `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddProductToCartRequest) Reset() {
	*x = AddProductToCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductToCartRequest) ProtoMessage() {}

func (x *AddProductToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductToCartRequest.ProtoReflect.Descriptor instead.
func (*AddProductToCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductToCartRequest) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *AddProductToCartRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AddProductToCartRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *AddProductToCartRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProductToCartRequest) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *AddProductToCartRequest) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *AddProductToCartRequest) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *AddProductToCartRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddProductToCartRequest) GetSkuAttributes() *structpb.Struct {
	if x != nil {
		return x.SkuAttributes
	}
	return nil
}

func (x *AddProductToCartRequest) GetSkuThumbnailUrl() string {
	if x != nil {
		return x.SkuThumbnailUrl
	}
	return ""
}

func (x *AddProductToCartRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddProductToCartResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CartTotalQuantity uint32                 `protobuf:"varint,1,opt,name=cart_total_quantity,json=cartTotalQuantity,proto3" json:"cart_total_quantity,omitempty"` // 购物车当前商品总件数，方便前端直接刷新右上角小红点
	CartItemId        uint64                 `protobuf:"varint,2,opt,name=cart_item_id,json=cartItemId,proto3" json:"cart_item_id,omitempty"`                      // 该商品在购物车中的唯一记录 ID，方便前端后续进行修改或删除
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddProductToCartResponse) Reset() {
	*x = AddProductToCartResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductToCartResponse) ProtoMessage() {}

func (x *AddProductToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductToCartResponse.ProtoReflect.Descriptor instead.
func (*AddProductToCartResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductToCartResponse) GetCartTotalQuantity() uint32 {
	if x != nil {
		return x.CartTotalQuantity
	}
	return 0
}

func (x *AddProductToCartResponse) GetCartItemId() uint64 {
	if x != nil {
		return x.CartItemId
	}
	return 0
}

type RemoveProductToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         uint64                 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuId         uint64                 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	MerchantId    string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProductToCartRequest) Reset() {
	*x = RemoveProductToCartRequest{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProductToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProductToCartRequest) ProtoMessage() {}

func (x *RemoveProductToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProductToCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveProductToCartRequest) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveProductToCartRequest) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *RemoveProductToCartRequest) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *RemoveProductToCartRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *RemoveProductToCartRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RemoveProductToCartRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RemoveProductToCartResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CartTotalQuantity uint32                 `protobuf:"varint,1,opt,name=cart_total_quantity,json=cartTotalQuantity,proto3" json:"cart_total_quantity,omitempty"` // 删除后，购物车剩下的商品总件数（用于刷新右上角小红点）
	IsCartEmpty       bool                   `protobuf:"varint,2,opt,name=is_cart_empty,json=isCartEmpty,proto3" json:"is_cart_empty,omitempty"`                   // 购物车是否已经彻底空了（用于前端直接切换到“空购物车”占位图）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveProductToCartResponse) Reset() {
	*x = RemoveProductToCartResponse{}
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProductToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProductToCartResponse) ProtoMessage() {}

func (x *RemoveProductToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_cart_v1_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProductToCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveProductToCartResponse) Descriptor() ([]byte, []int) {
	return file_api_cart_v1_cart_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveProductToCartResponse) GetCartTotalQuantity() uint32 {
	if x != nil {
		return x.CartTotalQuantity
	}
	return 0
}

func (x *RemoveProductToCartResponse) GetIsCartEmpty() bool {
	if x != nil {
		return x.IsCartEmpty
	}
	return false
}

var File_api_cart_v1_cart_proto protoreflect.FileDescriptor

const file_api_cart_v1_cart_proto_rawDesc = "" +
	"\n" +
	"\x16api/cart/v1/cart.proto\x12\acart.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a#third_party/validate/validate.proto\"\x91\x03\n" +
	"\x17AddProductToCartRequest\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x04R\x05spuId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x04R\x05skuId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12\x1a\n" +
	"\bselected\x18\x05 \x01(\bR\bselected\x12\x19\n" +
	"\bspu_name\x18\x06 \x01(\tR\aspuName\x12\x19\n" +
	"\bsku_name\x18\a \x01(\tR\askuName\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12>\n" +
	"\x0esku_attributes\x18\t \x01(\v2\x17.google.protobuf.StructR\rskuAttributes\x12*\n" +
	"\x11sku_thumbnail_url\x18\n" +
	" \x01(\tR\x0fskuThumbnailUrl\x127\n" +
	"\x06status\x18\v \x01(\tB\x1f\xbaH\x1cr\x1aR\x06activeR\aexpiredR\adeletedR\x06status\"l\n" +
	"\x18AddProductToCartResponse\x12.\n" +
	"\x13cart_total_quantity\x18\x01 \x01(\rR\x11cartTotalQuantity\x12 \n" +
	"\fcart_item_id\x18\x02 \x01(\x04R\n" +
	"cartItemId\"\xc2\x01\n" +
	"\x1aRemoveProductToCartRequest\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\x04R\x05spuId\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\x04R\x05skuId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"q\n" +
	"\x1bRemoveProductToCartResponse\x12.\n" +
	"\x13cart_total_quantity\x18\x01 \x01(\rR\x11cartTotalQuantity\x12\"\n" +
	"\ris_cart_empty\x18\x02 \x01(\bR\visCartEmpty2\xcc\x01\n" +
	"\vCartService\x12Y\n" +
	"\x10AddProductToCart\x12 .cart.v1.AddProductToCartRequest\x1a!.cart.v1.AddProductToCartResponse\"\x00\x12b\n" +
	"\x13RemoveProductToCart\x12#.cart.v1.RemoveProductToCartRequest\x1a$.cart.v1.RemoveProductToCartResponse\"\x00B\x8e\x01\n" +
	"\vcom.cart.v1B\tCartProtoP\x01Z7github.com/lens077/ecommerce/backend/api/cart/v1;cartv1\xa2\x02\x03CXX\xaa\x02\aCart.V1\xca\x02\aCart\\V1\xe2\x02\x13Cart\\V1\\GPBMetadata\xea\x02\bCart::V1b\x06proto3"

var (
	file_api_cart_v1_cart_proto_rawDescOnce sync.Once
	file_api_cart_v1_cart_proto_rawDescData []byte
)

func file_api_cart_v1_cart_proto_rawDescGZIP() []byte {
	file_api_cart_v1_cart_proto_rawDescOnce.Do(func() {
		file_api_cart_v1_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)))
	})
	return file_api_cart_v1_cart_proto_rawDescData
}

var file_api_cart_v1_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_cart_v1_cart_proto_goTypes = []any{
	(*AddProductToCartRequest)(nil),     // 0: cart.v1.AddProductToCartRequest
	(*AddProductToCartResponse)(nil),    // 1: cart.v1.AddProductToCartResponse
	(*RemoveProductToCartRequest)(nil),  // 2: cart.v1.RemoveProductToCartRequest
	(*RemoveProductToCartResponse)(nil), // 3: cart.v1.RemoveProductToCartResponse
	(*structpb.Struct)(nil),             // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_api_cart_v1_cart_proto_depIdxs = []int32{
	4, // 0: cart.v1.AddProductToCartRequest.sku_attributes:type_name -> google.protobuf.Struct
	5, // 1: cart.v1.RemoveProductToCartRequest.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: cart.v1.CartService.AddProductToCart:input_type -> cart.v1.AddProductToCartRequest
	2, // 3: cart.v1.CartService.RemoveProductToCart:input_type -> cart.v1.RemoveProductToCartRequest
	1, // 4: cart.v1.CartService.AddProductToCart:output_type -> cart.v1.AddProductToCartResponse
	3, // 5: cart.v1.CartService.RemoveProductToCart:output_type -> cart.v1.RemoveProductToCartResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_cart_v1_cart_proto_init() }
func file_api_cart_v1_cart_proto_init() {
	if File_api_cart_v1_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cart_v1_cart_proto_rawDesc), len(file_api_cart_v1_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_cart_v1_cart_proto_goTypes,
		DependencyIndexes: file_api_cart_v1_cart_proto_depIdxs,
		MessageInfos:      file_api_cart_v1_cart_proto_msgTypes,
	}.Build()
	File_api_cart_v1_cart_proto = out.File
	file_api_cart_v1_cart_proto_goTypes = nil
	file_api_cart_v1_cart_proto_depIdxs = nil
}
