// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file api/user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../../casdoor/v1/user_pb";
import { file_api_casdoor_v1_user } from "../../casdoor/v1/user_pb";
import { file_third_party_validate_validate } from "../../../third_party/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/user/v1/user.proto.
 */
export const file_api_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChZhcGkvdXNlci92MS91c2VyLnByb3RvEgd1c2VyLnYxIkQKDVNpZ25JblJlcXVlc3QSGAoEY29kZRgBIAEoCUIKukgHcgUQARiAEBIZCgVzdGF0ZRgCIAEoCUIKukgHcgUQARiABCJDCg5TaWduSW5SZXNwb25zZRIYCgVzdGF0ZRgBIAEoCUIJukgGcgQQARhAEhcKBGRhdGEYAiABKAlCCbpIBnIEGICAASIUChJVc2VyUHJvZmlsZVJlcXVlc3QiPQoTVXNlclByb2ZpbGVSZXNwb25zZRImCgR1c2VyGAEgASgLMhAuY2FzZG9vci52MS5Vc2VyQga6SAPIAQEylgEKC1VzZXJTZXJ2aWNlEjsKBlNpZ25JbhIWLnVzZXIudjEuU2lnbkluUmVxdWVzdBoXLnVzZXIudjEuU2lnbkluUmVzcG9uc2UiABJKCgtVc2VyUHJvZmlsZRIbLnVzZXIudjEuVXNlclByb2ZpbGVSZXF1ZXN0GhwudXNlci52MS5Vc2VyUHJvZmlsZVJlc3BvbnNlIgBCjgEKC2NvbS51c2VyLnYxQglVc2VyUHJvdG9QAVo3Z2l0aHViLmNvbS9sZW5zMDc3L2Vjb21tZXJjZS9iYWNrZW5kL2FwaS91c2VyL3YxO3VzZXJ2MaICA1VYWKoCB1VzZXIuVjHKAgdVc2VyXFYx4gITVXNlclxWMVxHUEJNZXRhZGF0YeoCCFVzZXI6OlYxYgZwcm90bzM", [file_api_casdoor_v1_user, file_third_party_validate_validate]);

/**
 * @generated from message user.v1.SignInRequest
 */
export type SignInRequest = Message<"user.v1.SignInRequest"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;
};

/**
 * Describes the message user.v1.SignInRequest.
 * Use `create(SignInRequestSchema)` to create a new message.
 */
export const SignInRequestSchema: GenMessage<SignInRequest> = /*@__PURE__*/
  messageDesc(file_api_user_v1_user, 0);

/**
 * @generated from message user.v1.SignInResponse
 */
export type SignInResponse = Message<"user.v1.SignInResponse"> & {
  /**
   * @generated from field: string state = 1;
   */
  state: string;

  /**
   * @generated from field: string data = 2;
   */
  data: string;
};

/**
 * Describes the message user.v1.SignInResponse.
 * Use `create(SignInResponseSchema)` to create a new message.
 */
export const SignInResponseSchema: GenMessage<SignInResponse> = /*@__PURE__*/
  messageDesc(file_api_user_v1_user, 1);

/**
 * @generated from message user.v1.UserProfileRequest
 */
export type UserProfileRequest = Message<"user.v1.UserProfileRequest"> & {
};

/**
 * Describes the message user.v1.UserProfileRequest.
 * Use `create(UserProfileRequestSchema)` to create a new message.
 */
export const UserProfileRequestSchema: GenMessage<UserProfileRequest> = /*@__PURE__*/
  messageDesc(file_api_user_v1_user, 2);

/**
 * @generated from message user.v1.UserProfileResponse
 */
export type UserProfileResponse = Message<"user.v1.UserProfileResponse"> & {
  /**
   * @generated from field: casdoor.v1.User user = 1;
   */
  user?: User | undefined;
};

/**
 * Describes the message user.v1.UserProfileResponse.
 * Use `create(UserProfileResponseSchema)` to create a new message.
 */
export const UserProfileResponseSchema: GenMessage<UserProfileResponse> = /*@__PURE__*/
  messageDesc(file_api_user_v1_user, 3);

/**
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.SignIn
   */
  signIn: {
    methodKind: "unary";
    input: typeof SignInRequestSchema;
    output: typeof SignInResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.UserProfile
   */
  userProfile: {
    methodKind: "unary";
    input: typeof UserProfileRequestSchema;
    output: typeof UserProfileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_user_v1_user, 0);

