{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "go.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "go.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: go
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: CONSUL_ENABLED
              value: {{ .Values.environment.CONSUL_ENABLED }}
            - name: CONSUL_ADDR
              value: {{ .Values.environment.CONSUL_ADDR }}
            - name: CONSUL_PATH
              value: {{ .Values.environment.CONSUL_PATH }}
            - name: CONSUL_SCHEME
              value: {{ .Values.environment.CONSUL_SCHEME }}
            - name: CONSUL_INSECURE_SKIP_VERIFY
              value: {{ .Values.environment.CONSUL_INSECURE_SKIP_VERIFY }}
#          volumeMounts:
#            - name: data-volume
#              mountPath: /data
#      volumes:
#        - name: data-volume
#          persistentVolumeClaim:
#            claimName: connect-example-pvc
{{- end }}
