// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/behavior/v1/behavior.proto

package behaviorv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lens077/ecommerce/backend/api/behavior/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BehaviorServiceName is the fully-qualified name of the BehaviorService service.
	BehaviorServiceName = "behavior.v1.BehaviorService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BehaviorServiceTrackProcedure is the fully-qualified name of the BehaviorService's Track RPC.
	BehaviorServiceTrackProcedure = "/behavior.v1.BehaviorService/Track"
	// BehaviorServiceRecommendProcedure is the fully-qualified name of the BehaviorService's Recommend
	// RPC.
	BehaviorServiceRecommendProcedure = "/behavior.v1.BehaviorService/Recommend"
	// BehaviorServiceSimilarItemsProcedure is the fully-qualified name of the BehaviorService's
	// SimilarItems RPC.
	BehaviorServiceSimilarItemsProcedure = "/behavior.v1.BehaviorService/SimilarItems"
)

// BehaviorServiceClient is a client for the behavior.v1.BehaviorService service.
type BehaviorServiceClient interface {
	// Track 批量上报行为事件。
	// 前端离开页面时用 navigator.sendBeacon 以 Connect JSON 直接打这个方法,
	// 所以请求体必须是自包含的(不依赖自定义请求头)。
	Track(context.Context, *connect.Request[v1.TrackRequest]) (*connect.Response[v1.TrackResponse], error)
	// Recommend 拉推荐列表。登录用户走个性化召回,匿名/冷启动用会话内事件兜底。
	Recommend(context.Context, *connect.Request[v1.RecommendRequest]) (*connect.Response[v1.RecommendResponse], error)
	// SimilarItems 商品详情页的"相似商品",不依赖用户画像,冷启动可用。
	SimilarItems(context.Context, *connect.Request[v1.SimilarItemsRequest]) (*connect.Response[v1.SimilarItemsResponse], error)
}

// NewBehaviorServiceClient constructs a client for the behavior.v1.BehaviorService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBehaviorServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BehaviorServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	behaviorServiceMethods := v1.File_api_behavior_v1_behavior_proto.Services().ByName("BehaviorService").Methods()
	return &behaviorServiceClient{
		track: connect.NewClient[v1.TrackRequest, v1.TrackResponse](
			httpClient,
			baseURL+BehaviorServiceTrackProcedure,
			connect.WithSchema(behaviorServiceMethods.ByName("Track")),
			connect.WithClientOptions(opts...),
		),
		recommend: connect.NewClient[v1.RecommendRequest, v1.RecommendResponse](
			httpClient,
			baseURL+BehaviorServiceRecommendProcedure,
			connect.WithSchema(behaviorServiceMethods.ByName("Recommend")),
			connect.WithClientOptions(opts...),
		),
		similarItems: connect.NewClient[v1.SimilarItemsRequest, v1.SimilarItemsResponse](
			httpClient,
			baseURL+BehaviorServiceSimilarItemsProcedure,
			connect.WithSchema(behaviorServiceMethods.ByName("SimilarItems")),
			connect.WithClientOptions(opts...),
		),
	}
}

// behaviorServiceClient implements BehaviorServiceClient.
type behaviorServiceClient struct {
	track        *connect.Client[v1.TrackRequest, v1.TrackResponse]
	recommend    *connect.Client[v1.RecommendRequest, v1.RecommendResponse]
	similarItems *connect.Client[v1.SimilarItemsRequest, v1.SimilarItemsResponse]
}

// Track calls behavior.v1.BehaviorService.Track.
func (c *behaviorServiceClient) Track(ctx context.Context, req *connect.Request[v1.TrackRequest]) (*connect.Response[v1.TrackResponse], error) {
	return c.track.CallUnary(ctx, req)
}

// Recommend calls behavior.v1.BehaviorService.Recommend.
func (c *behaviorServiceClient) Recommend(ctx context.Context, req *connect.Request[v1.RecommendRequest]) (*connect.Response[v1.RecommendResponse], error) {
	return c.recommend.CallUnary(ctx, req)
}

// SimilarItems calls behavior.v1.BehaviorService.SimilarItems.
func (c *behaviorServiceClient) SimilarItems(ctx context.Context, req *connect.Request[v1.SimilarItemsRequest]) (*connect.Response[v1.SimilarItemsResponse], error) {
	return c.similarItems.CallUnary(ctx, req)
}

// BehaviorServiceHandler is an implementation of the behavior.v1.BehaviorService service.
type BehaviorServiceHandler interface {
	// Track 批量上报行为事件。
	// 前端离开页面时用 navigator.sendBeacon 以 Connect JSON 直接打这个方法,
	// 所以请求体必须是自包含的(不依赖自定义请求头)。
	Track(context.Context, *connect.Request[v1.TrackRequest]) (*connect.Response[v1.TrackResponse], error)
	// Recommend 拉推荐列表。登录用户走个性化召回,匿名/冷启动用会话内事件兜底。
	Recommend(context.Context, *connect.Request[v1.RecommendRequest]) (*connect.Response[v1.RecommendResponse], error)
	// SimilarItems 商品详情页的"相似商品",不依赖用户画像,冷启动可用。
	SimilarItems(context.Context, *connect.Request[v1.SimilarItemsRequest]) (*connect.Response[v1.SimilarItemsResponse], error)
}

// NewBehaviorServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBehaviorServiceHandler(svc BehaviorServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	behaviorServiceMethods := v1.File_api_behavior_v1_behavior_proto.Services().ByName("BehaviorService").Methods()
	behaviorServiceTrackHandler := connect.NewUnaryHandler(
		BehaviorServiceTrackProcedure,
		svc.Track,
		connect.WithSchema(behaviorServiceMethods.ByName("Track")),
		connect.WithHandlerOptions(opts...),
	)
	behaviorServiceRecommendHandler := connect.NewUnaryHandler(
		BehaviorServiceRecommendProcedure,
		svc.Recommend,
		connect.WithSchema(behaviorServiceMethods.ByName("Recommend")),
		connect.WithHandlerOptions(opts...),
	)
	behaviorServiceSimilarItemsHandler := connect.NewUnaryHandler(
		BehaviorServiceSimilarItemsProcedure,
		svc.SimilarItems,
		connect.WithSchema(behaviorServiceMethods.ByName("SimilarItems")),
		connect.WithHandlerOptions(opts...),
	)
	return "/behavior.v1.BehaviorService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BehaviorServiceTrackProcedure:
			behaviorServiceTrackHandler.ServeHTTP(w, r)
		case BehaviorServiceRecommendProcedure:
			behaviorServiceRecommendHandler.ServeHTTP(w, r)
		case BehaviorServiceSimilarItemsProcedure:
			behaviorServiceSimilarItemsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBehaviorServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBehaviorServiceHandler struct{}

func (UnimplementedBehaviorServiceHandler) Track(context.Context, *connect.Request[v1.TrackRequest]) (*connect.Response[v1.TrackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("behavior.v1.BehaviorService.Track is not implemented"))
}

func (UnimplementedBehaviorServiceHandler) Recommend(context.Context, *connect.Request[v1.RecommendRequest]) (*connect.Response[v1.RecommendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("behavior.v1.BehaviorService.Recommend is not implemented"))
}

func (UnimplementedBehaviorServiceHandler) SimilarItems(context.Context, *connect.Request[v1.SimilarItemsRequest]) (*connect.Response[v1.SimilarItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("behavior.v1.BehaviorService.SimilarItems is not implemented"))
}
