apiVersion: v1
kind: Service
metadata:
  name: ecommerce-config-service
spec:
  externalTrafficPolicy: Local
  selector:
    app: ecommerce-config
  ports:
    - protocol: TCP
      port: 30010
      targetPort: 30010
  type: LoadBalancer
