apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ccr.ccs.tencentyun.com/sumery/consumer-next
    newTag: "1.6.8"
    digest: sha256:5722fff562a00d9d8138318502d65dac8a13ce35282d7d92b3cdba40971e49c0
patches:
  - target:
      kind: Deployment
      name: consumer-next
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/env/1/name
        value: CONSUMER_NEXT_PUBLIC_URL
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: https://shop.apikv.com
