apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ccr.ccs.tencentyun.com/sumery/consumer-next
    newTag: "1.7.3"
    digest: sha256:6f1c0fff4a3e0e4f5dca894a7171b382ff3028bb4ac0c1f65f50bd6c549fd6d2
patches:
  - target:
      kind: Deployment
      name: consumer-next
    patch: |-
      - op: test
        path: /spec/template/spec/containers/0/env/1/name
        value: CONSUMER_NEXT_PUBLIC_URL
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: https://shop.apikv.com
