replicaCount: 1
enabled: true

global:
  configSource:
    enabled: true
    secretName: ecommerce-config-source-pre
    mountPath: /etc/ecommerce/config-source

image:
  repository: "ccr.ccs.tencentyun.com/sumery/cart"
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    http:
      enabled: true
      port: 30005
      targetPort: 30005
    grpc:
      enabled: false
      port: 30006
      targetPort: 30006

env: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
