### local
POST http://localhost:30001/healthz
Content-Type: application/json

### pre
POST http://192.168.3.118:30001/healthz
Content-Type: application/json

### k8s SignIn
POST http://192.168.3.118:30001/user.v1.UserService/SignIn
Content-Type: application/json

{
  "code": "1231",
  "state": "12313"
}

###
POST http://localhost:30001/user.v1.UserService/SignIn
Content-Type: application/json

{
  "code": "1231",
  "state": "12313"
}

### k8s 网关
POST http://192.168.3.114:8080/user.v1.UserService/SignIn
Content-Type: application/json

{
  "code": "1231",
  "state": "12313"
}

### Gateway GetUserProfile
# curl -v -X POST http://localhost:8080/user.v1.UserService/UserProfile \
# --header 'Content-Type: application/json' \ \
# --header 'Authorization: Bearer ***REMOVED-JWT***' \
# --data-raw '{}'

POST http://localhost:8080/user/v1.UserService/UserProfile
Content-Type: application/json
Authorization: Bearer ***REMOVED-JWT***

{}

### GetUserProfile
# curl -v -X POST http://localhost:30001/v1.UserService/UserProfile
#--header 'Content-Type: application/json'
#--header 'x-md-global-name: test'
#--data-raw '{}'
POST http://localhost:30001/v1.UserService/UserProfile
x-md-global-name: test
Content-Type: application/json

{}

###
