# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/user
    newTag: "1.7.2"
    digest: sha256:fa12e5997f57c0034c3bbaee838e8e052e4181705691f1ed2a2640bfe633094f
