### local
POST http://localhost:30004/order.v1.orderService/CreateOrder
Content-Type: application/json

{
  "orderNo": "ORDER202602240001"
}


### local CompleteOrder
POST http://localhost:30004/order.v1.orderService/CompleteOrder
Content-Type: application/json

{
  "orderNo": "ORDER202602240001"
}

### local
POST http://localhost:30004/healthz
Content-Type: application/json

### pre
#  --header 'Content-Type: application/json'
#  --data-raw '{}'
POST http://192.168.3.124:30004/healthz
Content-Type: application/json

### curl -v -X POST http://my.dev.test/check.v1.CheckService/Ready
#  --header 'Content-Type: application/json'
#  --data-raw '{}'
POST http://localhost:30004/user.v1.UserService/SignIn
Content-Type: application/json

{
  "code": "1231",
  "state": "12313"
}

### Gateway GetUserProfile
# curl -v -X POST http://localhost:8080/user.v1.UserService/UserProfile \
# --header 'Content-Type: application/json' \ \
# --header 'Authorization: Bearer ***REMOVED-JWT***' \
# --data-raw '{}'

POST http://localhost:8080/user/v1.UserService/UserProfile
Content-Type: application/json
Authorization: Bearer ***REMOVED-JWT***

{}

### GetUserProfile
# curl -v -X POST http://localhost:30004/v1.UserService/UserProfile
#--header 'Content-Type: application/json'
#--header 'x-md-global-name: test'
#--data-raw '{}'
POST http://localhost:30004/v1.UserService/UserProfile
x-md-global-name: test
Content-Type: application/json

{}

###
