### 网关
POST http://localhost:8080/product/product.v1.ProductService/GetProductDetail
Content-Type: application/json

{"spuCode": "iphone-15-pro"}

### 直连后端
POST http://localhost:30003/product.v1.ProductService/GetProductDetail
Content-Type: application/json

{"spuCode": "iphone-15-pro"}

###
