// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	//GetProductDetail
	//
	//  SELECT s.id          AS spu_id,
	//         s.name,
	//         s.spu_code,
	//         s.specs       AS common_specs, -- 通用规格
	//         json_agg(k.*) AS skus
	//  FROM products.spus s
	//           JOIN products.skus k ON s.id = k.spu_id
	//  WHERE s.spu_code = $1
	//    AND s.status = 'online'
	//  GROUP BY s.id
	GetProductDetail(ctx context.Context, spuCode string) (GetProductDetailRow, error)
}

var _ Querier = (*Queries)(nil)
