apiVersion: v1
kind: Service
metadata:
  name: ecommerce-merchant-service
  namespace: ecommerce
spec:
  selector:
    app: ecommerce-merchant
  ports:
    - protocol: TCP
      port: 30007
      targetPort: 30007
  type: LoadBalancer
