replicaCount: 1
enabled: true

image:
  repository: "ccr.ccs.tencentyun.com/sumery/order"
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    http:
      enabled: true
      port: 30011
      targetPort: 30011
    grpc:
      enabled: false
      port: 30012
      targetPort: 30012

env: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
