// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/product/v1/product.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_third_party_validate_validate } from "../../../third_party/validate/validate_pb";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/product/v1/product.proto.
 */
export const file_api_product_v1_product: GenFile = /*@__PURE__*/
  fileDesc("ChxhcGkvcHJvZHVjdC92MS9wcm9kdWN0LnByb3RvEgpwcm9kdWN0LnYxIisKF0dldFByb2R1Y3REZXRhaWxSZXF1ZXN0EhAKCHNwdV9jb2RlGAEgASgJIlAKGEdldFByb2R1Y3REZXRhaWxSZXNwb25zZRI0Cg5wcm9kdWN0X2RldGFpbBgBIAEoCzIcLnByb2R1Y3QudjEuUHJvZHVjdFNwdURldGFpbCKXAQoQUHJvZHVjdFNwdURldGFpbBIOCgZzcHVfaWQYASABKAMSDAoEbmFtZRgCIAEoCRIQCghzcHVfY29kZRgDIAEoCRItCgxjb21tb25fc3BlY3MYBCABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0EiQKBHNrdXMYBSADKAsyFi5wcm9kdWN0LnYxLlByb2R1Y3RTa3UigQEKClByb2R1Y3RTa3USDgoGc2t1X2lkGAEgASgDEhAKCHNrdV9jb2RlGAIgASgJEg0KBXByaWNlGAMgASgBEg0KBXN0b2NrGAQgASgFEiYKBWF0dHJzGAUgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdBILCgNpbWcYBiABKAkycQoOUHJvZHVjdFNlcnZpY2USXwoQR2V0UHJvZHVjdERldGFpbBIjLnByb2R1Y3QudjEuR2V0UHJvZHVjdERldGFpbFJlcXVlc3QaJC5wcm9kdWN0LnYxLkdldFByb2R1Y3REZXRhaWxSZXNwb25zZSIAQqYBCg5jb20ucHJvZHVjdC52MUIMUHJvZHVjdFByb3RvUAFaPWdpdGh1Yi5jb20vc3VubWVyeS9lY29tbWVyY2UvYmFja2VuZC9hcGkvcHJvZHVjdC92MTtwcm9kdWN0djGiAgNQWFiqAgpQcm9kdWN0LlYxygIKUHJvZHVjdFxWMeICFlByb2R1Y3RcVjFcR1BCTWV0YWRhdGHqAgtQcm9kdWN0OjpWMWIGcHJvdG8z", [file_google_protobuf_struct, file_google_protobuf_timestamp, file_third_party_validate_validate]);

/**
 * @generated from message product.v1.GetProductDetailRequest
 */
export type GetProductDetailRequest = Message<"product.v1.GetProductDetailRequest"> & {
  /**
   * @generated from field: string spu_code = 1;
   */
  spuCode: string;
};

/**
 * Describes the message product.v1.GetProductDetailRequest.
 * Use `create(GetProductDetailRequestSchema)` to create a new message.
 */
export const GetProductDetailRequestSchema: GenMessage<GetProductDetailRequest> = /*@__PURE__*/
  messageDesc(file_api_product_v1_product, 0);

/**
 * @generated from message product.v1.GetProductDetailResponse
 */
export type GetProductDetailResponse = Message<"product.v1.GetProductDetailResponse"> & {
  /**
   * @generated from field: product.v1.ProductSpuDetail product_detail = 1;
   */
  productDetail?: ProductSpuDetail;
};

/**
 * Describes the message product.v1.GetProductDetailResponse.
 * Use `create(GetProductDetailResponseSchema)` to create a new message.
 */
export const GetProductDetailResponseSchema: GenMessage<GetProductDetailResponse> = /*@__PURE__*/
  messageDesc(file_api_product_v1_product, 1);

/**
 * @generated from message product.v1.ProductSpuDetail
 */
export type ProductSpuDetail = Message<"product.v1.ProductSpuDetail"> & {
  /**
   * @generated from field: int64 spu_id = 1;
   */
  spuId: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string spu_code = 3;
   */
  spuCode: string;

  /**
   * 使用 google.protobuf.Struct 来匹配 map[string]any
   *
   * @generated from field: google.protobuf.Struct common_specs = 4;
   */
  commonSpecs?: JsonObject;

  /**
   * @generated from field: repeated product.v1.ProductSku skus = 5;
   */
  skus: ProductSku[];
};

/**
 * Describes the message product.v1.ProductSpuDetail.
 * Use `create(ProductSpuDetailSchema)` to create a new message.
 */
export const ProductSpuDetailSchema: GenMessage<ProductSpuDetail> = /*@__PURE__*/
  messageDesc(file_api_product_v1_product, 2);

/**
 * @generated from message product.v1.ProductSku
 */
export type ProductSku = Message<"product.v1.ProductSku"> & {
  /**
   * @generated from field: int64 sku_id = 1;
   */
  skuId: bigint;

  /**
   * @generated from field: string sku_code = 2;
   */
  skuCode: string;

  /**
   * @generated from field: double price = 3;
   */
  price: number;

  /**
   * @generated from field: int32 stock = 4;
   */
  stock: number;

  /**
   * 使用 google.protobuf.Struct 处理动态 SKU 属性
   *
   * @generated from field: google.protobuf.Struct attrs = 5;
   */
  attrs?: JsonObject;

  /**
   * @generated from field: string img = 6;
   */
  img: string;
};

/**
 * Describes the message product.v1.ProductSku.
 * Use `create(ProductSkuSchema)` to create a new message.
 */
export const ProductSkuSchema: GenMessage<ProductSku> = /*@__PURE__*/
  messageDesc(file_api_product_v1_product, 3);

/**
 * @generated from service product.v1.ProductService
 */
export const ProductService: GenService<{
  /**
   * @generated from rpc product.v1.ProductService.GetProductDetail
   */
  getProductDetail: {
    methodKind: "unary";
    input: typeof GetProductDetailRequestSchema;
    output: typeof GetProductDetailResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_product_v1_product, 0);

