// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ApproveApplication = `-- name: ApproveApplication :exec
UPDATE merchants.merchant_application
SET status        = $1,
    audit_comment = $2,
    reviewed_at   = $3,
    updated_at    = $4
`

type ApproveApplicationParams struct {
	Status       string
	AuditComment *string
	ReviewedAt   pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// ApproveApplication
//
//	UPDATE merchants.merchant_application
//	SET status        = $1,
//	    audit_comment = $2,
//	    reviewed_at   = $3,
//	    updated_at    = $4
func (q *Queries) ApproveApplication(ctx context.Context, arg ApproveApplicationParams) error {
	_, err := q.db.Exec(ctx, ApproveApplication,
		arg.Status,
		arg.AuditComment,
		arg.ReviewedAt,
		arg.UpdatedAt,
	)
	return err
}

const GetApplication = `-- name: GetApplication :one
SELECT id, application_id, company_name, credit_code, legal_person, legal_person_id, contact_phone, business_license_url, legal_person_id_front_url, legal_person_id_back_url, category_ids, status, reject_reason, audit_comment, submitted_at, reviewed_at, remark, created_at, updated_at
FROM merchants.merchant_application
WHERE application_id = $1
`

// GetApplication
//
//	SELECT id, application_id, company_name, credit_code, legal_person, legal_person_id, contact_phone, business_license_url, legal_person_id_front_url, legal_person_id_back_url, category_ids, status, reject_reason, audit_comment, submitted_at, reviewed_at, remark, created_at, updated_at
//	FROM merchants.merchant_application
//	WHERE application_id = $1
func (q *Queries) GetApplication(ctx context.Context, applicationID string) (MerchantsMerchantApplication, error) {
	row := q.db.QueryRow(ctx, GetApplication, applicationID)
	var i MerchantsMerchantApplication
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.CompanyName,
		&i.CreditCode,
		&i.LegalPerson,
		&i.LegalPersonID,
		&i.ContactPhone,
		&i.BusinessLicenseUrl,
		&i.LegalPersonIDFrontUrl,
		&i.LegalPersonIDBackUrl,
		&i.CategoryIds,
		&i.Status,
		&i.RejectReason,
		&i.AuditComment,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetMerchantAgreement = `-- name: GetMerchantAgreement :one
SELECT default_version, version, effective_date, content_url
FROM merchants.agreement
`

// GetMerchantAgreement
//
//	SELECT default_version, version, effective_date, content_url
//	FROM merchants.agreement
func (q *Queries) GetMerchantAgreement(ctx context.Context) (MerchantsAgreement, error) {
	row := q.db.QueryRow(ctx, GetMerchantAgreement)
	var i MerchantsAgreement
	err := row.Scan(
		&i.DefaultVersion,
		&i.Version,
		&i.EffectiveDate,
		&i.ContentUrl,
	)
	return i, err
}

const SubmitApplication = `-- name: SubmitApplication :exec
INSERT INTO merchants.merchant_application(application_id, company_name, credit_code, legal_person, legal_person_id,
                                           contact_phone, business_license_url, legal_person_id_front_url,
                                           legal_person_id_back_url, category_ids, reviewed_at, remark)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12)
`

type SubmitApplicationParams struct {
	ApplicationID         string
	CompanyName           string
	CreditCode            string
	LegalPerson           string
	LegalPersonID         string
	ContactPhone          string
	BusinessLicenseUrl    *string
	LegalPersonIDFrontUrl *string
	LegalPersonIDBackUrl  *string
	CategoryIds           []int64
	ReviewedAt            pgtype.Timestamptz
	Remark                *string
}

// SubmitApplication
//
//	INSERT INTO merchants.merchant_application(application_id, company_name, credit_code, legal_person, legal_person_id,
//	                                           contact_phone, business_license_url, legal_person_id_front_url,
//	                                           legal_person_id_back_url, category_ids, reviewed_at, remark)
//	VALUES ($1,
//	        $2,
//	        $3,
//	        $4,
//	        $5,
//	        $6,
//	        $7,
//	        $8,
//	        $9,
//	        $10,
//	        $11,
//	        $12)
func (q *Queries) SubmitApplication(ctx context.Context, arg SubmitApplicationParams) error {
	_, err := q.db.Exec(ctx, SubmitApplication,
		arg.ApplicationID,
		arg.CompanyName,
		arg.CreditCode,
		arg.LegalPerson,
		arg.LegalPersonID,
		arg.ContactPhone,
		arg.BusinessLicenseUrl,
		arg.LegalPersonIDFrontUrl,
		arg.LegalPersonIDBackUrl,
		arg.CategoryIds,
		arg.ReviewedAt,
		arg.Remark,
	)
	return err
}
