// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type MerchantsMerchant struct {
	ID            int64
	MerchantID    string
	ApplicationID string
	CompanyName   string
	CreditCode    string
	LegalPerson   string
	ContactPhone  string
	Status        string
	ShopName      *string
	ShopLogoUrl   *string
	OwnerUserID   string
	ActivatedAt   pgtype.Timestamptz
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MerchantsMerchantApplication struct {
	ID                    int64
	ApplicationID         string
	CompanyName           string
	CreditCode            string
	LegalPerson           string
	LegalPersonID         string
	ContactPhone          string
	BusinessLicenseUrl    *string
	LegalPersonIDFrontUrl *string
	LegalPersonIDBackUrl  *string
	CategoryIds           []int64
	Status                string
	RejectReason          *string
	AuditComment          *string
	SubmittedAt           time.Time
	ReviewedAt            pgtype.Timestamptz
	Remark                *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
}
