// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"
)

type Querier interface {
	//GetApplication
	//
	//  SELECT id, application_id, company_name, credit_code, legal_person, legal_person_id, contact_phone, business_license_url, legal_person_id_front_url, legal_person_id_back_url, category_ids, status, reject_reason, audit_comment, submitted_at, reviewed_at, remark, created_at, updated_at
	//  FROM merchants.merchant_application
	//  WHERE application_id = $1
	GetApplication(ctx context.Context, applicationID string) (MerchantsMerchantApplication, error)
	//SubmitApplication
	//
	//  INSERT INTO merchants.merchant_application(application_id, company_name, credit_code, legal_person, legal_person_id,
	//                                             contact_phone, business_license_url, legal_person_id_front_url,
	//                                             legal_person_id_back_url, category_ids, reviewed_at, remark)
	//  VALUES ($1,
	//          $2,
	//          $3,
	//          $4,
	//          $5,
	//          $6,
	//          $7,
	//          $8,
	//          $9,
	//          $10,
	//          $11,
	//          $12)
	SubmitApplication(ctx context.Context, arg SubmitApplicationParams) error
}

var _ Querier = (*Queries)(nil)
