# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/cart
    newTag: "1.7.1"
    digest: sha256:89bbbd66dc0fa1ecb2c35480fbe8baeec4dc5516abbb241109095be9a4c67d59
