# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/cart
    newTag: "1.7.5"
    digest: sha256:dd5f663c9c1bb6f6422c9bb206207fa84919e022c9da001623127f4e76011fdb
