# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/cart
    newTag: "1.7.3"
    digest: sha256:3d4eabf86f67a268644694ee15564d5a287e37d3aa9a1643bbf9baf391922549
