/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CallbackIndexRouteImport } from './routes/callback/index'
import { Route as ProductSpuCodeRouteImport } from './routes/product/$spuCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSpuCodeRoute = ProductSpuCodeRouteImport.update({
  id: '/product/$spuCode',
  path: '/product/$spuCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$spuCode': typeof ProductSpuCodeRoute
  '/callback/': typeof CallbackIndexRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$spuCode': typeof ProductSpuCodeRoute
  '/callback': typeof CallbackIndexRoute
  '/cart': typeof CartIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$spuCode': typeof ProductSpuCodeRoute
  '/callback/': typeof CallbackIndexRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product/$spuCode'
    | '/callback/'
    | '/cart/'
    | '/categories/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$spuCode'
    | '/callback'
    | '/cart'
    | '/categories'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/product/$spuCode'
    | '/callback/'
    | '/cart/'
    | '/categories/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductSpuCodeRoute: typeof ProductSpuCodeRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback/'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$spuCode': {
      id: '/product/$spuCode'
      path: '/product/$spuCode'
      fullPath: '/product/$spuCode'
      preLoaderRoute: typeof ProductSpuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductSpuCodeRoute: ProductSpuCodeRoute,
  CallbackIndexRoute: CallbackIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
