# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/address
    newTag: "1.7.2"
    digest: sha256:5575479e7b00e684e04474515a2fb8d619359da8e1635f429b808b5f792bb7b1
