// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: services/config/internal/conf/v1/conf.proto

package confv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Observability *Observability         `protobuf:"bytes,3,opt,name=observability,proto3" json:"observability,omitempty"`
	Discovery     *Discovery             `protobuf:"bytes,4,opt,name=discovery,proto3" json:"discovery,omitempty"`
	Log           *Log                   `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

func (x *Bootstrap) GetDiscovery() *Discovery {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Framework     *Log_Framework         `protobuf:"bytes,1,opt,name=framework,proto3" json:"framework,omitempty"`
	Application   *Log_Application       `protobuf:"bytes,2,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Log) GetFramework() *Log_Framework {
	if x != nil {
		return x.Framework
	}
	return nil
}

func (x *Log) GetApplication() *Log_Application {
	if x != nil {
		return x.Application
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Http          *Server_HTTP           `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Cors          *Server_Cors           `protobuf:"bytes,3,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetCors() *Server_Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Cache         *Data_Cache            `protobuf:"bytes,2,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetCache() *Data_Cache {
	if x != nil {
		return x.Cache
	}
	return nil
}

type Observability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         *Observability_Trace   `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	Metric        *Observability_Metric  `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Log           *Observability_Logging `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Enable        bool                   `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Observability) GetTrace() *Observability_Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Observability) GetMetric() *Observability_Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *Observability) GetLog() *Observability_Logging {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Observability) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type Discovery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consul        *Discovery_Consul      `protobuf:"bytes,1,opt,name=consul,proto3" json:"consul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discovery) Reset() {
	*x = Discovery{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery) ProtoMessage() {}

func (x *Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery.ProtoReflect.Descriptor instead.
func (*Discovery) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Discovery) GetConsul() *Discovery_Consul {
	if x != nil {
		return x.Consul
	}
	return nil
}

type Log_Framework struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	ErrorLevel    string                 `protobuf:"bytes,3,opt,name=error_level,json=errorLevel,proto3" json:"error_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_Framework) Reset() {
	*x = Log_Framework{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_Framework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Framework) ProtoMessage() {}

func (x *Log_Framework) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Framework.ProtoReflect.Descriptor instead.
func (*Log_Framework) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Log_Framework) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Log_Framework) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Log_Framework) GetErrorLevel() string {
	if x != nil {
		return x.ErrorLevel
	}
	return ""
}

type Log_Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_Application) Reset() {
	*x = Log_Application{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Application) ProtoMessage() {}

func (x *Log_Application) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Application.ProtoReflect.Descriptor instead.
func (*Log_Application) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Log_Application) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Log_Application) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,1,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,2,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	IdleTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=idle_timeout,json=idleTimeout,proto3" json:"idle_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Server_HTTP) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Server_HTTP) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Server_HTTP) GetIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.IdleTimeout
	}
	return nil
}

type Server_Cors struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllowedOrigins []string               `protobuf:"bytes,1,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Server_Cors) Reset() {
	*x = Server_Cors{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Cors) ProtoMessage() {}

func (x *Server_Cors) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Cors.ProtoReflect.Descriptor instead.
func (*Server_Cors) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Server_Cors) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

type Data_Database struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Postgres      *Data_Database_Postgres `protobuf:"bytes,1,opt,name=postgres,proto3" json:"postgres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Data_Database) GetPostgres() *Data_Database_Postgres {
	if x != nil {
		return x.Postgres
	}
	return nil
}

type Data_Cache struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Redis         *Data_Cache_Redis      `protobuf:"bytes,1,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Cache) Reset() {
	*x = Data_Cache{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Cache) ProtoMessage() {}

func (x *Data_Cache) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Cache.ProtoReflect.Descriptor instead.
func (*Data_Cache) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Data_Cache) GetRedis() *Data_Cache_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Data_Database_Postgres struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Host          string                               `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                               `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                               `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DbName        string                               `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Timezone      string                               `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Pool          *Data_Database_Postgres_DatabasePool `protobuf:"bytes,8,opt,name=pool,proto3" json:"pool,omitempty"`
	Tls           *Data_Database_Postgres_Tls          `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database_Postgres) Reset() {
	*x = Data_Database_Postgres{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database_Postgres) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database_Postgres) ProtoMessage() {}

func (x *Data_Database_Postgres) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database_Postgres.ProtoReflect.Descriptor instead.
func (*Data_Database_Postgres) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *Data_Database_Postgres) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Data_Database_Postgres) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Data_Database_Postgres) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Data_Database_Postgres) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Database_Postgres) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *Data_Database_Postgres) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Data_Database_Postgres) GetPool() *Data_Database_Postgres_DatabasePool {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *Data_Database_Postgres) GetTls() *Data_Database_Postgres_Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Data_Database_Postgres_DatabasePool struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxConns        uint32                 `protobuf:"varint,1,opt,name=max_conns,json=maxConns,proto3" json:"max_conns,omitempty"`
	MinConns        uint32                 `protobuf:"varint,2,opt,name=min_conns,json=minConns,proto3" json:"min_conns,omitempty"`
	MaxConnLifetime *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_conn_lifetime,json=maxConnLifetime,proto3" json:"max_conn_lifetime,omitempty"`
	MaxConnIdleTime *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_conn_idle_time,json=maxConnIdleTime,proto3" json:"max_conn_idle_time,omitempty"`
	PingTimeout     *durationpb.Duration   `protobuf:"bytes,5,opt,name=ping_timeout,json=pingTimeout,proto3" json:"ping_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database_Postgres_DatabasePool) Reset() {
	*x = Data_Database_Postgres_DatabasePool{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database_Postgres_DatabasePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database_Postgres_DatabasePool) ProtoMessage() {}

func (x *Data_Database_Postgres_DatabasePool) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database_Postgres_DatabasePool.ProtoReflect.Descriptor instead.
func (*Data_Database_Postgres_DatabasePool) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 0, 0, 0}
}

func (x *Data_Database_Postgres_DatabasePool) GetMaxConns() uint32 {
	if x != nil {
		return x.MaxConns
	}
	return 0
}

func (x *Data_Database_Postgres_DatabasePool) GetMinConns() uint32 {
	if x != nil {
		return x.MinConns
	}
	return 0
}

func (x *Data_Database_Postgres_DatabasePool) GetMaxConnLifetime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnLifetime
	}
	return nil
}

func (x *Data_Database_Postgres_DatabasePool) GetMaxConnIdleTime() *durationpb.Duration {
	if x != nil {
		return x.MaxConnIdleTime
	}
	return nil
}

func (x *Data_Database_Postgres_DatabasePool) GetPingTimeout() *durationpb.Duration {
	if x != nil {
		return x.PingTimeout
	}
	return nil
}

type Data_Database_Postgres_Tls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	SslMode       string                 `protobuf:"bytes,6,opt,name=ssl_mode,json=sslMode,proto3" json:"ssl_mode,omitempty"`
	CaPem         string                 `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Database_Postgres_Tls) Reset() {
	*x = Data_Database_Postgres_Tls{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database_Postgres_Tls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database_Postgres_Tls) ProtoMessage() {}

func (x *Data_Database_Postgres_Tls) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database_Postgres_Tls.ProtoReflect.Descriptor instead.
func (*Data_Database_Postgres_Tls) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 0, 0, 1}
}

func (x *Data_Database_Postgres_Tls) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Data_Database_Postgres_Tls) GetSslMode() string {
	if x != nil {
		return x.SslMode
	}
	return ""
}

func (x *Data_Database_Postgres_Tls) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

type Data_Cache_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Db            uint32                 `protobuf:"varint,5,opt,name=db,proto3" json:"db,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,6,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,7,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,8,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	PoolSize      uint32                 `protobuf:"varint,9,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	MinIdleConns  uint32                 `protobuf:"varint,10,opt,name=min_idle_conns,json=minIdleConns,proto3" json:"min_idle_conns,omitempty"`
	Tls           *Data_Cache_Redis_Tls  `protobuf:"bytes,11,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Cache_Redis) Reset() {
	*x = Data_Cache_Redis{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Cache_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Cache_Redis) ProtoMessage() {}

func (x *Data_Cache_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Cache_Redis.ProtoReflect.Descriptor instead.
func (*Data_Cache_Redis) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 1, 0}
}

func (x *Data_Cache_Redis) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Data_Cache_Redis) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Data_Cache_Redis) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_Cache_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Cache_Redis) GetDb() uint32 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Data_Cache_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Data_Cache_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Cache_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Cache_Redis) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *Data_Cache_Redis) GetMinIdleConns() uint32 {
	if x != nil {
		return x.MinIdleConns
	}
	return 0
}

func (x *Data_Cache_Redis) GetTls() *Data_Cache_Redis_Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Data_Cache_Redis_Tls struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enable             bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	CaPem              string                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,3,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Data_Cache_Redis_Tls) Reset() {
	*x = Data_Cache_Redis_Tls{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Cache_Redis_Tls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Cache_Redis_Tls) ProtoMessage() {}

func (x *Data_Cache_Redis_Tls) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Cache_Redis_Tls.ProtoReflect.Descriptor instead.
func (*Data_Cache_Redis_Tls) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{3, 1, 0, 0}
}

func (x *Data_Cache_Redis_Tls) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Data_Cache_Redis_Tls) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *Data_Cache_Redis_Tls) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

type Observability_Trace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tls           *Observability_Tls     `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Trace) Reset() {
	*x = Observability_Trace{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Trace) ProtoMessage() {}

func (x *Observability_Trace) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Trace.ProtoReflect.Descriptor instead.
func (*Observability_Trace) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Observability_Trace) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Trace) GetTls() *Observability_Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Observability_Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tls           *Observability_Tls     `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Metric) Reset() {
	*x = Observability_Metric{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Metric) ProtoMessage() {}

func (x *Observability_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Metric.ProtoReflect.Descriptor instead.
func (*Observability_Metric) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Observability_Metric) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Metric) GetTls() *Observability_Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Observability_Logging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Tls           *Observability_Tls     `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability_Logging) Reset() {
	*x = Observability_Logging{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Logging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Logging) ProtoMessage() {}

func (x *Observability_Logging) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Logging.ProtoReflect.Descriptor instead.
func (*Observability_Logging) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Observability_Logging) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Observability_Logging) GetTls() *Observability_Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Observability_Tls struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enable             bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	CaPem              string                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,3,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Observability_Tls) Reset() {
	*x = Observability_Tls{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability_Tls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability_Tls) ProtoMessage() {}

func (x *Observability_Tls) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability_Tls.ProtoReflect.Descriptor instead.
func (*Observability_Tls) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{4, 3}
}

func (x *Observability_Tls) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Observability_Tls) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

func (x *Observability_Tls) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

type Discovery_Consul struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Addr          string                  `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Scheme        string                  `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	HealthCheck   bool                    `protobuf:"varint,3,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Tls           *Discovery_Consul_Tls   `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	Check         *Discovery_Consul_Check `protobuf:"bytes,5,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discovery_Consul) Reset() {
	*x = Discovery_Consul{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery_Consul) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery_Consul) ProtoMessage() {}

func (x *Discovery_Consul) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery_Consul.ProtoReflect.Descriptor instead.
func (*Discovery_Consul) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Discovery_Consul) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Discovery_Consul) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Discovery_Consul) GetHealthCheck() bool {
	if x != nil {
		return x.HealthCheck
	}
	return false
}

func (x *Discovery_Consul) GetTls() *Discovery_Consul_Tls {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *Discovery_Consul) GetCheck() *Discovery_Consul_Check {
	if x != nil {
		return x.Check
	}
	return nil
}

type Discovery_Consul_Tls struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Enable             bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,2,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	CaPem              string                 `protobuf:"bytes,3,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Discovery_Consul_Tls) Reset() {
	*x = Discovery_Consul_Tls{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery_Consul_Tls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery_Consul_Tls) ProtoMessage() {}

func (x *Discovery_Consul_Tls) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery_Consul_Tls.ProtoReflect.Descriptor instead.
func (*Discovery_Consul_Tls) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *Discovery_Consul_Tls) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Discovery_Consul_Tls) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

func (x *Discovery_Consul_Tls) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

type Discovery_Consul_Check struct {
	state                          protoimpl.MessageState      `protogen:"open.v1"`
	Ttl                            *Discovery_Consul_Check_TTL `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	DeregisterCriticalServiceAfter string                      `protobuf:"bytes,2,opt,name=deregister_critical_service_after,json=deregisterCriticalServiceAfter,proto3" json:"deregister_critical_service_after,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Discovery_Consul_Check) Reset() {
	*x = Discovery_Consul_Check{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery_Consul_Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery_Consul_Check) ProtoMessage() {}

func (x *Discovery_Consul_Check) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery_Consul_Check.ProtoReflect.Descriptor instead.
func (*Discovery_Consul_Check) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{5, 0, 1}
}

func (x *Discovery_Consul_Check) GetTtl() *Discovery_Consul_Check_TTL {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Discovery_Consul_Check) GetDeregisterCriticalServiceAfter() string {
	if x != nil {
		return x.DeregisterCriticalServiceAfter
	}
	return ""
}

type Discovery_Consul_Check_TTL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      string                 `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	PingInterval  *durationpb.Duration   `protobuf:"bytes,2,opt,name=ping_interval,json=pingInterval,proto3" json:"ping_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Discovery_Consul_Check_TTL) Reset() {
	*x = Discovery_Consul_Check_TTL{}
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Discovery_Consul_Check_TTL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery_Consul_Check_TTL) ProtoMessage() {}

func (x *Discovery_Consul_Check_TTL) ProtoReflect() protoreflect.Message {
	mi := &file_services_config_internal_conf_v1_conf_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery_Consul_Check_TTL.ProtoReflect.Descriptor instead.
func (*Discovery_Consul_Check_TTL) Descriptor() ([]byte, []int) {
	return file_services_config_internal_conf_v1_conf_proto_rawDescGZIP(), []int{5, 0, 1, 0}
}

func (x *Discovery_Consul_Check_TTL) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *Discovery_Consul_Check_TTL) GetPingInterval() *durationpb.Duration {
	if x != nil {
		return x.PingInterval
	}
	return nil
}

var File_services_config_internal_conf_v1_conf_proto protoreflect.FileDescriptor

const file_services_config_internal_conf_v1_conf_proto_rawDesc = "" +
	"\n" +
	"+services/config/internal/conf/v1/conf.proto\x12\aconf.v1\x1a#third_party/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\"\x8f\x02\n" +
	"\tBootstrap\x12/\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.conf.v1.ServerB\x06\xbaH\x03\xc8\x01\x01R\x06server\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\r.conf.v1.DataB\x06\xbaH\x03\xc8\x01\x01R\x04data\x12D\n" +
	"\robservability\x18\x03 \x01(\v2\x16.conf.v1.ObservabilityB\x06\xbaH\x03\xc8\x01\x00R\robservability\x128\n" +
	"\tdiscovery\x18\x04 \x01(\v2\x12.conf.v1.DiscoveryB\x06\xbaH\x03\xc8\x01\x00R\tdiscovery\x12&\n" +
	"\x03log\x18\x05 \x01(\v2\f.conf.v1.LogB\x06\xbaH\x03\xc8\x01\x01R\x03log\"\xea\x03\n" +
	"\x03Log\x124\n" +
	"\tframework\x18\x01 \x01(\v2\x16.conf.v1.Log.FrameworkR\tframework\x12:\n" +
	"\vapplication\x18\x02 \x01(\v2\x18.conf.v1.Log.ApplicationR\vapplication\x1a\xe5\x01\n" +
	"\tFramework\x12,\n" +
	"\x06format\x18\x01 \x01(\tB\x14\xbaH\x11r\x0fR\aconsoleR\x04jsonR\x06format\x12R\n" +
	"\tlog_level\x18\x02 \x01(\tB5\xbaH2r0R\x05debugR\x04infoR\x04warnR\x05errorR\x06dpanicR\x05panicR\x05fatalR\blogLevel\x12V\n" +
	"\verror_level\x18\x03 \x01(\tB5\xbaH2r0R\x05debugR\x04infoR\x04warnR\x05errorR\x06dpanicR\x05panicR\x05fatalR\n" +
	"errorLevel\x1a\x88\x01\n" +
	"\vApplication\x12,\n" +
	"\x06format\x18\x01 \x01(\tB\x14\xbaH\x11r\x0fR\aconsoleR\x04jsonR\x06format\x12K\n" +
	"\x05level\x18\x02 \x01(\tB5\xbaH2r0R\x05debugR\x04infoR\x04warnR\x05errorR\x06dpanicR\x05panicR\x05fatalR\x05level\"\xc0\x03\n" +
	"\x06Server\x12&\n" +
	"\x04addr\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x92\x02\a0.0.0.0\xa8\x01\x01R\x04addr\x12(\n" +
	"\x04http\x18\x02 \x01(\v2\x14.conf.v1.Server.HTTPR\x04http\x12(\n" +
	"\x04cors\x18\x03 \x01(\v2\x14.conf.v1.Server.CorsR\x04cors\x1a\xe6\x01\n" +
	"\x04HTTP\x12H\n" +
	"\fread_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\vreadTimeout\x12J\n" +
	"\rwrite_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\fwriteTimeout\x12H\n" +
	"\fidle_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\vidleTimeout\x1aQ\n" +
	"\x04Cors\x12I\n" +
	"\x0fallowed_origins\x18\x01 \x03(\tB \xbaH\x1dr\x1b\x92\x02\x15http://localhost:3000\x80\x02\x01R\x0eallowedOrigins\"\xb4\r\n" +
	"\x04Data\x122\n" +
	"\bdatabase\x18\x01 \x01(\v2\x16.conf.v1.Data.DatabaseR\bdatabase\x12)\n" +
	"\x05cache\x18\x02 \x01(\v2\x13.conf.v1.Data.CacheR\x05cache\x1a\x9b\a\n" +
	"\bDatabase\x12;\n" +
	"\bpostgres\x18\x01 \x01(\v2\x1f.conf.v1.Data.Database.PostgresR\bpostgres\x1a\xd1\x06\n" +
	"\bPostgres\x12\x1c\n" +
	"\x04host\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xa8\x01\x01R\x04host\x12\x1c\n" +
	"\x04port\x18\x02 \x01(\rB\b\xbaH\x05\x1a\x03@\xb8*R\x04port\x12$\n" +
	"\x04user\x18\x03 \x01(\tB\x10\xbaH\rr\v\x92\x02\bpostgresR\x04user\x12,\n" +
	"\bpassword\x18\x04 \x01(\tB\x10\xbaH\rr\v\x92\x02\bpostgresR\bpassword\x12)\n" +
	"\adb_name\x18\x05 \x01(\tB\x10\xbaH\rr\v\x92\x02\bpostgresR\x06dbName\x121\n" +
	"\btimezone\x18\a \x01(\tB\x15\xbaH\x12r\x10\x92\x02\rAsia/ShanghaiR\btimezone\x12@\n" +
	"\x04pool\x18\b \x01(\v2,.conf.v1.Data.Database.Postgres.DatabasePoolR\x04pool\x125\n" +
	"\x03tls\x18\t \x01(\v2#.conf.v1.Data.Database.Postgres.TlsR\x03tls\x1a\xcb\x02\n" +
	"\fDatabasePool\x12$\n" +
	"\tmax_conns\x18\x01 \x01(\rB\a\xbaH\x04\x1a\x02(\x01R\bmaxConns\x12$\n" +
	"\tmin_conns\x18\x02 \x01(\rB\a\xbaH\x04\x1a\x02(\x01R\bminConns\x12Q\n" +
	"\x11max_conn_lifetime\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\x0fmaxConnLifetime\x12R\n" +
	"\x12max_conn_idle_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\x0fmaxConnIdleTime\x12H\n" +
	"\fping_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\vpingTimeout\x1a\x8f\x01\n" +
	"\x03Tls\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12Y\n" +
	"\bssl_mode\x18\x06 \x01(\tB>\xbaH;r9R\adisableR\x05allowR\x06preferR\arequireR\tverify-caR\vverify-fullR\asslMode\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\tR\x05caPem\x1a\xae\x05\n" +
	"\x05Cache\x12/\n" +
	"\x05redis\x18\x01 \x01(\v2\x19.conf.v1.Data.Cache.RedisR\x05redis\x1a\xf3\x04\n" +
	"\x05Redis\x12\x1c\n" +
	"\x04host\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xa8\x01\x01R\x04host\x12\x1c\n" +
	"\x04port\x18\x02 \x01(\rB\b\xbaH\x05\x1a\x03@\xeb1R\x04port\x12+\n" +
	"\busername\x18\x03 \x01(\tB\x0f\xbaH\fr\n" +
	"\x92\x02\adefaultR\busername\x12,\n" +
	"\bpassword\x18\x04 \x01(\tB\x10\xbaH\rr\v\x92\x02\bpasswordR\bpassword\x12\x0e\n" +
	"\x02db\x18\x05 \x01(\rR\x02db\x12H\n" +
	"\fdial_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\vdialTimeout\x12H\n" +
	"\fread_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\vreadTimeout\x12J\n" +
	"\rwrite_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x01R\fwriteTimeout\x12\x1b\n" +
	"\tpool_size\x18\t \x01(\rR\bpoolSize\x12-\n" +
	"\x0emin_idle_conns\x18\n" +
	" \x01(\rB\a\xbaH\x04\x1a\x02(\x01R\fminIdleConns\x12/\n" +
	"\x03tls\x18\v \x01(\v2\x1d.conf.v1.Data.Cache.Redis.TlsR\x03tls\x1af\n" +
	"\x03Tls\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem\x120\n" +
	"\x14insecure_skip_verify\x18\x03 \x01(\bR\x12insecureSkipVerify\"\xc6\x04\n" +
	"\rObservability\x122\n" +
	"\x05trace\x18\x01 \x01(\v2\x1c.conf.v1.Observability.TraceR\x05trace\x125\n" +
	"\x06metric\x18\x02 \x01(\v2\x1d.conf.v1.Observability.MetricR\x06metric\x120\n" +
	"\x03log\x18\x03 \x01(\v2\x1e.conf.v1.Observability.LoggingR\x03log\x12\x16\n" +
	"\x06enable\x18\x04 \x01(\bR\x06enable\x1a[\n" +
	"\x05Trace\x12$\n" +
	"\bendpoint\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\bendpoint\x12,\n" +
	"\x03tls\x18\x02 \x01(\v2\x1a.conf.v1.Observability.TlsR\x03tls\x1a\\\n" +
	"\x06Metric\x12$\n" +
	"\bendpoint\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\bendpoint\x12,\n" +
	"\x03tls\x18\x02 \x01(\v2\x1a.conf.v1.Observability.TlsR\x03tls\x1a]\n" +
	"\aLogging\x12$\n" +
	"\bendpoint\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\bendpoint\x12,\n" +
	"\x03tls\x18\x02 \x01(\v2\x1a.conf.v1.Observability.TlsR\x03tls\x1af\n" +
	"\x03Tls\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem\x120\n" +
	"\x14insecure_skip_verify\x18\x03 \x01(\bR\x12insecureSkipVerify\"\xed\x04\n" +
	"\tDiscovery\x121\n" +
	"\x06consul\x18\x01 \x01(\v2\x19.conf.v1.Discovery.ConsulR\x06consul\x1a\xac\x04\n" +
	"\x06Consul\x12\x1c\n" +
	"\x04addr\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x80\x02\x01R\x04addr\x12\x16\n" +
	"\x06scheme\x18\x02 \x01(\tR\x06scheme\x12!\n" +
	"\fhealth_check\x18\x03 \x01(\bR\vhealthCheck\x12/\n" +
	"\x03tls\x18\x04 \x01(\v2\x1d.conf.v1.Discovery.Consul.TlsR\x03tls\x125\n" +
	"\x05check\x18\x05 \x01(\v2\x1f.conf.v1.Discovery.Consul.CheckR\x05check\x1af\n" +
	"\x03Tls\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x120\n" +
	"\x14insecure_skip_verify\x18\x02 \x01(\bR\x12insecureSkipVerify\x12\x15\n" +
	"\x06ca_pem\x18\x03 \x01(\tR\x05caPem\x1a\xf8\x01\n" +
	"\x05Check\x125\n" +
	"\x03ttl\x18\x01 \x01(\v2#.conf.v1.Discovery.Consul.Check.TTLR\x03ttl\x12I\n" +
	"!deregister_critical_service_after\x18\x02 \x01(\tR\x1ederegisterCriticalServiceAfter\x1am\n" +
	"\x03TTL\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\tR\bduration\x12J\n" +
	"\rping_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\n" +
	"\xbaH\a\xaa\x01\x042\x02\b\x05R\fpingIntervalB\xa3\x01\n" +
	"\vcom.conf.v1B\tConfProtoP\x01ZLgithub.com/lens077/ecommerce/backend/services/config/internal/conf/v1;confv1\xa2\x02\x03CXX\xaa\x02\aConf.V1\xca\x02\aConf\\V1\xe2\x02\x13Conf\\V1\\GPBMetadata\xea\x02\bConf::V1b\x06proto3"

var (
	file_services_config_internal_conf_v1_conf_proto_rawDescOnce sync.Once
	file_services_config_internal_conf_v1_conf_proto_rawDescData []byte
)

func file_services_config_internal_conf_v1_conf_proto_rawDescGZIP() []byte {
	file_services_config_internal_conf_v1_conf_proto_rawDescOnce.Do(func() {
		file_services_config_internal_conf_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_config_internal_conf_v1_conf_proto_rawDesc), len(file_services_config_internal_conf_v1_conf_proto_rawDesc)))
	})
	return file_services_config_internal_conf_v1_conf_proto_rawDescData
}

var file_services_config_internal_conf_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_services_config_internal_conf_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),                           // 0: conf.v1.Bootstrap
	(*Log)(nil),                                 // 1: conf.v1.Log
	(*Server)(nil),                              // 2: conf.v1.Server
	(*Data)(nil),                                // 3: conf.v1.Data
	(*Observability)(nil),                       // 4: conf.v1.Observability
	(*Discovery)(nil),                           // 5: conf.v1.Discovery
	(*Log_Framework)(nil),                       // 6: conf.v1.Log.Framework
	(*Log_Application)(nil),                     // 7: conf.v1.Log.Application
	(*Server_HTTP)(nil),                         // 8: conf.v1.Server.HTTP
	(*Server_Cors)(nil),                         // 9: conf.v1.Server.Cors
	(*Data_Database)(nil),                       // 10: conf.v1.Data.Database
	(*Data_Cache)(nil),                          // 11: conf.v1.Data.Cache
	(*Data_Database_Postgres)(nil),              // 12: conf.v1.Data.Database.Postgres
	(*Data_Database_Postgres_DatabasePool)(nil), // 13: conf.v1.Data.Database.Postgres.DatabasePool
	(*Data_Database_Postgres_Tls)(nil),          // 14: conf.v1.Data.Database.Postgres.Tls
	(*Data_Cache_Redis)(nil),                    // 15: conf.v1.Data.Cache.Redis
	(*Data_Cache_Redis_Tls)(nil),                // 16: conf.v1.Data.Cache.Redis.Tls
	(*Observability_Trace)(nil),                 // 17: conf.v1.Observability.Trace
	(*Observability_Metric)(nil),                // 18: conf.v1.Observability.Metric
	(*Observability_Logging)(nil),               // 19: conf.v1.Observability.Logging
	(*Observability_Tls)(nil),                   // 20: conf.v1.Observability.Tls
	(*Discovery_Consul)(nil),                    // 21: conf.v1.Discovery.Consul
	(*Discovery_Consul_Tls)(nil),                // 22: conf.v1.Discovery.Consul.Tls
	(*Discovery_Consul_Check)(nil),              // 23: conf.v1.Discovery.Consul.Check
	(*Discovery_Consul_Check_TTL)(nil),          // 24: conf.v1.Discovery.Consul.Check.TTL
	(*durationpb.Duration)(nil),                 // 25: google.protobuf.Duration
}
var file_services_config_internal_conf_v1_conf_proto_depIdxs = []int32{
	2,  // 0: conf.v1.Bootstrap.server:type_name -> conf.v1.Server
	3,  // 1: conf.v1.Bootstrap.data:type_name -> conf.v1.Data
	4,  // 2: conf.v1.Bootstrap.observability:type_name -> conf.v1.Observability
	5,  // 3: conf.v1.Bootstrap.discovery:type_name -> conf.v1.Discovery
	1,  // 4: conf.v1.Bootstrap.log:type_name -> conf.v1.Log
	6,  // 5: conf.v1.Log.framework:type_name -> conf.v1.Log.Framework
	7,  // 6: conf.v1.Log.application:type_name -> conf.v1.Log.Application
	8,  // 7: conf.v1.Server.http:type_name -> conf.v1.Server.HTTP
	9,  // 8: conf.v1.Server.cors:type_name -> conf.v1.Server.Cors
	10, // 9: conf.v1.Data.database:type_name -> conf.v1.Data.Database
	11, // 10: conf.v1.Data.cache:type_name -> conf.v1.Data.Cache
	17, // 11: conf.v1.Observability.trace:type_name -> conf.v1.Observability.Trace
	18, // 12: conf.v1.Observability.metric:type_name -> conf.v1.Observability.Metric
	19, // 13: conf.v1.Observability.log:type_name -> conf.v1.Observability.Logging
	21, // 14: conf.v1.Discovery.consul:type_name -> conf.v1.Discovery.Consul
	25, // 15: conf.v1.Server.HTTP.read_timeout:type_name -> google.protobuf.Duration
	25, // 16: conf.v1.Server.HTTP.write_timeout:type_name -> google.protobuf.Duration
	25, // 17: conf.v1.Server.HTTP.idle_timeout:type_name -> google.protobuf.Duration
	12, // 18: conf.v1.Data.Database.postgres:type_name -> conf.v1.Data.Database.Postgres
	15, // 19: conf.v1.Data.Cache.redis:type_name -> conf.v1.Data.Cache.Redis
	13, // 20: conf.v1.Data.Database.Postgres.pool:type_name -> conf.v1.Data.Database.Postgres.DatabasePool
	14, // 21: conf.v1.Data.Database.Postgres.tls:type_name -> conf.v1.Data.Database.Postgres.Tls
	25, // 22: conf.v1.Data.Database.Postgres.DatabasePool.max_conn_lifetime:type_name -> google.protobuf.Duration
	25, // 23: conf.v1.Data.Database.Postgres.DatabasePool.max_conn_idle_time:type_name -> google.protobuf.Duration
	25, // 24: conf.v1.Data.Database.Postgres.DatabasePool.ping_timeout:type_name -> google.protobuf.Duration
	25, // 25: conf.v1.Data.Cache.Redis.dial_timeout:type_name -> google.protobuf.Duration
	25, // 26: conf.v1.Data.Cache.Redis.read_timeout:type_name -> google.protobuf.Duration
	25, // 27: conf.v1.Data.Cache.Redis.write_timeout:type_name -> google.protobuf.Duration
	16, // 28: conf.v1.Data.Cache.Redis.tls:type_name -> conf.v1.Data.Cache.Redis.Tls
	20, // 29: conf.v1.Observability.Trace.tls:type_name -> conf.v1.Observability.Tls
	20, // 30: conf.v1.Observability.Metric.tls:type_name -> conf.v1.Observability.Tls
	20, // 31: conf.v1.Observability.Logging.tls:type_name -> conf.v1.Observability.Tls
	22, // 32: conf.v1.Discovery.Consul.tls:type_name -> conf.v1.Discovery.Consul.Tls
	23, // 33: conf.v1.Discovery.Consul.check:type_name -> conf.v1.Discovery.Consul.Check
	24, // 34: conf.v1.Discovery.Consul.Check.ttl:type_name -> conf.v1.Discovery.Consul.Check.TTL
	25, // 35: conf.v1.Discovery.Consul.Check.TTL.ping_interval:type_name -> google.protobuf.Duration
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_services_config_internal_conf_v1_conf_proto_init() }
func file_services_config_internal_conf_v1_conf_proto_init() {
	if File_services_config_internal_conf_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_config_internal_conf_v1_conf_proto_rawDesc), len(file_services_config_internal_conf_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_config_internal_conf_v1_conf_proto_goTypes,
		DependencyIndexes: file_services_config_internal_conf_v1_conf_proto_depIdxs,
		MessageInfos:      file_services_config_internal_conf_v1_conf_proto_msgTypes,
	}.Build()
	File_services_config_internal_conf_v1_conf_proto = out.File
	file_services_config_internal_conf_v1_conf_proto_goTypes = nil
	file_services_config_internal_conf_v1_conf_proto_depIdxs = nil
}
