// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/payment/v1/payment.proto

package paymentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/lens077/ecommerce/backend/api/payment/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaymentServiceName is the fully-qualified name of the PaymentService service.
	PaymentServiceName = "payment.v1.PaymentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaymentServiceCreatePaymentProcedure is the fully-qualified name of the PaymentService's
	// CreatePayment RPC.
	PaymentServiceCreatePaymentProcedure = "/payment.v1.PaymentService/CreatePayment"
	// PaymentServiceGetPaymentStatusProcedure is the fully-qualified name of the PaymentService's
	// GetPaymentStatus RPC.
	PaymentServiceGetPaymentStatusProcedure = "/payment.v1.PaymentService/GetPaymentStatus"
	// PaymentServiceHandlePaymentNotifyProcedure is the fully-qualified name of the PaymentService's
	// HandlePaymentNotify RPC.
	PaymentServiceHandlePaymentNotifyProcedure = "/payment.v1.PaymentService/HandlePaymentNotify"
	// PaymentServiceHandlePaymentCallbackProcedure is the fully-qualified name of the PaymentService's
	// HandlePaymentCallback RPC.
	PaymentServiceHandlePaymentCallbackProcedure = "/payment.v1.PaymentService/HandlePaymentCallback"
)

// PaymentServiceClient is a client for the payment.v1.PaymentService service.
type PaymentServiceClient interface {
	// 创建支付订单
	CreatePayment(context.Context, *connect.Request[v1.CreatePaymentRequest]) (*connect.Response[v1.CreatePaymentResponse], error)
	// 查询支付状态
	GetPaymentStatus(context.Context, *connect.Request[v1.GetPaymentStatusRequest]) (*connect.Response[v1.GetPaymentStatusResponse], error)
	// 处理支付回调通知
	//
	//	rpc HandlePaymentNotify (HandlePaymentNotifyRequest) returns (HandlePaymentNotifyResponse) {
	HandlePaymentNotify(context.Context, *connect.Request[v1.UrlValues]) (*connect.Response[v1.HandlePaymentNotifyResponse], error)
	// 支付成功后的回调处理
	HandlePaymentCallback(context.Context, *connect.Request[v1.HandlePaymentCallbackRequest]) (*connect.Response[v1.HandlePaymentCallbackResponse], error)
}

// NewPaymentServiceClient constructs a client for the payment.v1.PaymentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaymentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaymentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paymentServiceMethods := v1.File_api_payment_v1_payment_proto.Services().ByName("PaymentService").Methods()
	return &paymentServiceClient{
		createPayment: connect.NewClient[v1.CreatePaymentRequest, v1.CreatePaymentResponse](
			httpClient,
			baseURL+PaymentServiceCreatePaymentProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("CreatePayment")),
			connect.WithClientOptions(opts...),
		),
		getPaymentStatus: connect.NewClient[v1.GetPaymentStatusRequest, v1.GetPaymentStatusResponse](
			httpClient,
			baseURL+PaymentServiceGetPaymentStatusProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("GetPaymentStatus")),
			connect.WithClientOptions(opts...),
		),
		handlePaymentNotify: connect.NewClient[v1.UrlValues, v1.HandlePaymentNotifyResponse](
			httpClient,
			baseURL+PaymentServiceHandlePaymentNotifyProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("HandlePaymentNotify")),
			connect.WithClientOptions(opts...),
		),
		handlePaymentCallback: connect.NewClient[v1.HandlePaymentCallbackRequest, v1.HandlePaymentCallbackResponse](
			httpClient,
			baseURL+PaymentServiceHandlePaymentCallbackProcedure,
			connect.WithSchema(paymentServiceMethods.ByName("HandlePaymentCallback")),
			connect.WithClientOptions(opts...),
		),
	}
}

// paymentServiceClient implements PaymentServiceClient.
type paymentServiceClient struct {
	createPayment         *connect.Client[v1.CreatePaymentRequest, v1.CreatePaymentResponse]
	getPaymentStatus      *connect.Client[v1.GetPaymentStatusRequest, v1.GetPaymentStatusResponse]
	handlePaymentNotify   *connect.Client[v1.UrlValues, v1.HandlePaymentNotifyResponse]
	handlePaymentCallback *connect.Client[v1.HandlePaymentCallbackRequest, v1.HandlePaymentCallbackResponse]
}

// CreatePayment calls payment.v1.PaymentService.CreatePayment.
func (c *paymentServiceClient) CreatePayment(ctx context.Context, req *connect.Request[v1.CreatePaymentRequest]) (*connect.Response[v1.CreatePaymentResponse], error) {
	return c.createPayment.CallUnary(ctx, req)
}

// GetPaymentStatus calls payment.v1.PaymentService.GetPaymentStatus.
func (c *paymentServiceClient) GetPaymentStatus(ctx context.Context, req *connect.Request[v1.GetPaymentStatusRequest]) (*connect.Response[v1.GetPaymentStatusResponse], error) {
	return c.getPaymentStatus.CallUnary(ctx, req)
}

// HandlePaymentNotify calls payment.v1.PaymentService.HandlePaymentNotify.
func (c *paymentServiceClient) HandlePaymentNotify(ctx context.Context, req *connect.Request[v1.UrlValues]) (*connect.Response[v1.HandlePaymentNotifyResponse], error) {
	return c.handlePaymentNotify.CallUnary(ctx, req)
}

// HandlePaymentCallback calls payment.v1.PaymentService.HandlePaymentCallback.
func (c *paymentServiceClient) HandlePaymentCallback(ctx context.Context, req *connect.Request[v1.HandlePaymentCallbackRequest]) (*connect.Response[v1.HandlePaymentCallbackResponse], error) {
	return c.handlePaymentCallback.CallUnary(ctx, req)
}

// PaymentServiceHandler is an implementation of the payment.v1.PaymentService service.
type PaymentServiceHandler interface {
	// 创建支付订单
	CreatePayment(context.Context, *connect.Request[v1.CreatePaymentRequest]) (*connect.Response[v1.CreatePaymentResponse], error)
	// 查询支付状态
	GetPaymentStatus(context.Context, *connect.Request[v1.GetPaymentStatusRequest]) (*connect.Response[v1.GetPaymentStatusResponse], error)
	// 处理支付回调通知
	//
	//	rpc HandlePaymentNotify (HandlePaymentNotifyRequest) returns (HandlePaymentNotifyResponse) {
	HandlePaymentNotify(context.Context, *connect.Request[v1.UrlValues]) (*connect.Response[v1.HandlePaymentNotifyResponse], error)
	// 支付成功后的回调处理
	HandlePaymentCallback(context.Context, *connect.Request[v1.HandlePaymentCallbackRequest]) (*connect.Response[v1.HandlePaymentCallbackResponse], error)
}

// NewPaymentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaymentServiceHandler(svc PaymentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paymentServiceMethods := v1.File_api_payment_v1_payment_proto.Services().ByName("PaymentService").Methods()
	paymentServiceCreatePaymentHandler := connect.NewUnaryHandler(
		PaymentServiceCreatePaymentProcedure,
		svc.CreatePayment,
		connect.WithSchema(paymentServiceMethods.ByName("CreatePayment")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceGetPaymentStatusHandler := connect.NewUnaryHandler(
		PaymentServiceGetPaymentStatusProcedure,
		svc.GetPaymentStatus,
		connect.WithSchema(paymentServiceMethods.ByName("GetPaymentStatus")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceHandlePaymentNotifyHandler := connect.NewUnaryHandler(
		PaymentServiceHandlePaymentNotifyProcedure,
		svc.HandlePaymentNotify,
		connect.WithSchema(paymentServiceMethods.ByName("HandlePaymentNotify")),
		connect.WithHandlerOptions(opts...),
	)
	paymentServiceHandlePaymentCallbackHandler := connect.NewUnaryHandler(
		PaymentServiceHandlePaymentCallbackProcedure,
		svc.HandlePaymentCallback,
		connect.WithSchema(paymentServiceMethods.ByName("HandlePaymentCallback")),
		connect.WithHandlerOptions(opts...),
	)
	return "/payment.v1.PaymentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaymentServiceCreatePaymentProcedure:
			paymentServiceCreatePaymentHandler.ServeHTTP(w, r)
		case PaymentServiceGetPaymentStatusProcedure:
			paymentServiceGetPaymentStatusHandler.ServeHTTP(w, r)
		case PaymentServiceHandlePaymentNotifyProcedure:
			paymentServiceHandlePaymentNotifyHandler.ServeHTTP(w, r)
		case PaymentServiceHandlePaymentCallbackProcedure:
			paymentServiceHandlePaymentCallbackHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaymentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaymentServiceHandler struct{}

func (UnimplementedPaymentServiceHandler) CreatePayment(context.Context, *connect.Request[v1.CreatePaymentRequest]) (*connect.Response[v1.CreatePaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.CreatePayment is not implemented"))
}

func (UnimplementedPaymentServiceHandler) GetPaymentStatus(context.Context, *connect.Request[v1.GetPaymentStatusRequest]) (*connect.Response[v1.GetPaymentStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.GetPaymentStatus is not implemented"))
}

func (UnimplementedPaymentServiceHandler) HandlePaymentNotify(context.Context, *connect.Request[v1.UrlValues]) (*connect.Response[v1.HandlePaymentNotifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.HandlePaymentNotify is not implemented"))
}

func (UnimplementedPaymentServiceHandler) HandlePaymentCallback(context.Context, *connect.Request[v1.HandlePaymentCallbackRequest]) (*connect.Response[v1.HandlePaymentCallbackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("payment.v1.PaymentService.HandlePaymentCallback is not implemented"))
}
