// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/merchant/v1/merchant.proto

package merchantv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商家入驻申请状态
type ApplicationStatus int32

const (
	ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED    ApplicationStatus = 0 // 未指定（默认值，无效）
	ApplicationStatus_APPLICATION_STATUS_PENDING_REVIEW ApplicationStatus = 1 // 待审核
	ApplicationStatus_APPLICATION_STATUS_APPROVED       ApplicationStatus = 2 // 已通过
	ApplicationStatus_APPLICATION_STATUS_REJECTED       ApplicationStatus = 3 // 已驳回
	ApplicationStatus_APPLICATION_STATUS_ACTIVATED      ApplicationStatus = 4 // 已激活（商家完成首次设置并激活店铺）
)

// Enum value maps for ApplicationStatus.
var (
	ApplicationStatus_name = map[int32]string{
		0: "APPLICATION_STATUS_UNSPECIFIED",
		1: "APPLICATION_STATUS_PENDING_REVIEW",
		2: "APPLICATION_STATUS_APPROVED",
		3: "APPLICATION_STATUS_REJECTED",
		4: "APPLICATION_STATUS_ACTIVATED",
	}
	ApplicationStatus_value = map[string]int32{
		"APPLICATION_STATUS_UNSPECIFIED":    0,
		"APPLICATION_STATUS_PENDING_REVIEW": 1,
		"APPLICATION_STATUS_APPROVED":       2,
		"APPLICATION_STATUS_REJECTED":       3,
		"APPLICATION_STATUS_ACTIVATED":      4,
	}
)

func (x ApplicationStatus) Enum() *ApplicationStatus {
	p := new(ApplicationStatus)
	*p = x
	return p
}

func (x ApplicationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_merchant_v1_merchant_proto_enumTypes[0].Descriptor()
}

func (ApplicationStatus) Type() protoreflect.EnumType {
	return &file_api_merchant_v1_merchant_proto_enumTypes[0]
}

func (x ApplicationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationStatus.Descriptor instead.
func (ApplicationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{0}
}

type SubmitApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公司名称
	CompanyName string `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	// 统一社会信用代码
	CreditCode string `protobuf:"bytes,2,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"`
	// 法人姓名
	LegalPerson string `protobuf:"bytes,3,opt,name=legal_person,json=legalPerson,proto3" json:"legal_person,omitempty"`
	// 法人身份证号
	LegalPersonId string `protobuf:"bytes,4,opt,name=legal_person_id,json=legalPersonId,proto3" json:"legal_person_id,omitempty"`
	// 联系电话
	ContactPhone string `protobuf:"bytes,5,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	// 营业执照图片URL
	BusinessLicenseUrl string `protobuf:"bytes,6,opt,name=business_license_url,json=businessLicenseUrl,proto3" json:"business_license_url,omitempty"`
	// 法人身份证正面图片URL
	LegalPersonIdFrontUrl string `protobuf:"bytes,7,opt,name=legal_person_id_front_url,json=legalPersonIdFrontUrl,proto3" json:"legal_person_id_front_url,omitempty"`
	// 法人身份证反面图片URL
	LegalPersonIdBackUrl string `protobuf:"bytes,8,opt,name=legal_person_id_back_url,json=legalPersonIdBackUrl,proto3" json:"legal_person_id_back_url,omitempty"`
	// 申请经营类目ID列表
	CategoryIds []int64 `protobuf:"varint,9,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	// 备注
	Remark        string `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationRequest) Reset() {
	*x = SubmitApplicationRequest{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationRequest) ProtoMessage() {}

func (x *SubmitApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationRequest.ProtoReflect.Descriptor instead.
func (*SubmitApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitApplicationRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *SubmitApplicationRequest) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *SubmitApplicationRequest) GetLegalPerson() string {
	if x != nil {
		return x.LegalPerson
	}
	return ""
}

func (x *SubmitApplicationRequest) GetLegalPersonId() string {
	if x != nil {
		return x.LegalPersonId
	}
	return ""
}

func (x *SubmitApplicationRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *SubmitApplicationRequest) GetBusinessLicenseUrl() string {
	if x != nil {
		return x.BusinessLicenseUrl
	}
	return ""
}

func (x *SubmitApplicationRequest) GetLegalPersonIdFrontUrl() string {
	if x != nil {
		return x.LegalPersonIdFrontUrl
	}
	return ""
}

func (x *SubmitApplicationRequest) GetLegalPersonIdBackUrl() string {
	if x != nil {
		return x.LegalPersonIdBackUrl
	}
	return ""
}

func (x *SubmitApplicationRequest) GetCategoryIds() []int64 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *SubmitApplicationRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type SubmitApplicationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 申请ID
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// 当前状态 (pending_review)
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationResponse) Reset() {
	*x = SubmitApplicationResponse{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationResponse) ProtoMessage() {}

func (x *SubmitApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationResponse.ProtoReflect.Descriptor instead.
func (*SubmitApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitApplicationResponse) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *SubmitApplicationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ApproveApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 申请ID
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// 审核备注，可选
	AuditComment  string `protobuf:"bytes,2,opt,name=audit_comment,json=auditComment,proto3" json:"audit_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveApplicationRequest) Reset() {
	*x = ApproveApplicationRequest{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveApplicationRequest) ProtoMessage() {}

func (x *ApproveApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveApplicationRequest.ProtoReflect.Descriptor instead.
func (*ApproveApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApproveApplicationRequest) GetAuditComment() string {
	if x != nil {
		return x.AuditComment
	}
	return ""
}

type ApproveApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveApplicationResponse) Reset() {
	*x = ApproveApplicationResponse{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveApplicationResponse) ProtoMessage() {}

func (x *ApproveApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveApplicationResponse.ProtoReflect.Descriptor instead.
func (*ApproveApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{3}
}

type RejectApplicationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 申请ID
	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// 驳回原因，必填
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectApplicationRequest) Reset() {
	*x = RejectApplicationRequest{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectApplicationRequest) ProtoMessage() {}

func (x *RejectApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectApplicationRequest.ProtoReflect.Descriptor instead.
func (*RejectApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{4}
}

func (x *RejectApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RejectApplicationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RejectApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectApplicationResponse) Reset() {
	*x = RejectApplicationResponse{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectApplicationResponse) ProtoMessage() {}

func (x *RejectApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectApplicationResponse.ProtoReflect.Descriptor instead.
func (*RejectApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{5}
}

// 查询申请状态请求
type GetApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationRequest) Reset() {
	*x = GetApplicationRequest{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationRequest) ProtoMessage() {}

func (x *GetApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{6}
}

func (x *GetApplicationRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type GetApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Status        ApplicationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=merchant.v1.ApplicationStatus" json:"status,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CreditCode    string                 `protobuf:"bytes,4,opt,name=credit_code,json=creditCode,proto3" json:"credit_code,omitempty"`
	LegalPerson   string                 `protobuf:"bytes,5,opt,name=legal_person,json=legalPerson,proto3" json:"legal_person,omitempty"`
	ContactPhone  string                 `protobuf:"bytes,6,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	RejectReason  string                 `protobuf:"bytes,7,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"` // 仅当 status = REJECTED 时有值
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationResponse) Reset() {
	*x = GetApplicationResponse{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationResponse) ProtoMessage() {}

func (x *GetApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{7}
}

func (x *GetApplicationResponse) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *GetApplicationResponse) GetStatus() ApplicationStatus {
	if x != nil {
		return x.Status
	}
	return ApplicationStatus_APPLICATION_STATUS_UNSPECIFIED
}

func (x *GetApplicationResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GetApplicationResponse) GetCreditCode() string {
	if x != nil {
		return x.CreditCode
	}
	return ""
}

func (x *GetApplicationResponse) GetLegalPerson() string {
	if x != nil {
		return x.LegalPerson
	}
	return ""
}

func (x *GetApplicationResponse) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *GetApplicationResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *GetApplicationResponse) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

func (x *GetApplicationResponse) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

// 激活商家请求
type ActivateMerchantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ShopName      string                 `protobuf:"bytes,2,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	ShopLogoUrl   string                 `protobuf:"bytes,3,opt,name=shop_logo_url,json=shopLogoUrl,proto3" json:"shop_logo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateMerchantRequest) Reset() {
	*x = ActivateMerchantRequest{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateMerchantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateMerchantRequest) ProtoMessage() {}

func (x *ActivateMerchantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateMerchantRequest.ProtoReflect.Descriptor instead.
func (*ActivateMerchantRequest) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{8}
}

func (x *ActivateMerchantRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ActivateMerchantRequest) GetShopName() string {
	if x != nil {
		return x.ShopName
	}
	return ""
}

func (x *ActivateMerchantRequest) GetShopLogoUrl() string {
	if x != nil {
		return x.ShopLogoUrl
	}
	return ""
}

type ActivateMerchantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateMerchantResponse) Reset() {
	*x = ActivateMerchantResponse{}
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateMerchantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateMerchantResponse) ProtoMessage() {}

func (x *ActivateMerchantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_merchant_v1_merchant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateMerchantResponse.ProtoReflect.Descriptor instead.
func (*ActivateMerchantResponse) Descriptor() ([]byte, []int) {
	return file_api_merchant_v1_merchant_proto_rawDescGZIP(), []int{9}
}

var File_api_merchant_v1_merchant_proto protoreflect.FileDescriptor

const file_api_merchant_v1_merchant_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/merchant/v1/merchant.proto\x12\vmerchant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#third_party/validate/validate.proto\"\x9f\x04\n" +
	"\x18SubmitApplicationRequest\x12-\n" +
	"\fcompany_name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vcompanyName\x12*\n" +
	"\vcredit_code\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\n" +
	"creditCode\x12,\n" +
	"\flegal_person\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\vlegalPerson\x121\n" +
	"\x0flegal_person_id\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\rlegalPersonId\x12.\n" +
	"\rcontact_phone\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\fcontactPhone\x12:\n" +
	"\x14business_license_url\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\x12businessLicenseUrl\x12B\n" +
	"\x19legal_person_id_front_url\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\x15legalPersonIdFrontUrl\x12@\n" +
	"\x18legal_person_id_back_url\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\x14legalPersonIdBackUrl\x123\n" +
	"\fcategory_ids\x18\t \x03(\x03B\x10\xbaH\r\x92\x01\n" +
	"\x10d\x18\x01\"\x04\"\x02 \x00R\vcategoryIds\x12 \n" +
	"\x06remark\x18\n" +
	" \x01(\tB\b\xbaH\x05r\x03\x18\xd0\x0fR\x06remark\"\x9a\x01\n" +
	"\x19SubmitApplicationResponse\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12L\n" +
	"\x06status\x18\x02 \x01(\tB4\xbaH1r/R\x0epending_reviewR\bapprovedR\brejectedR\tactivatedR\x06status\"{\n" +
	"\x19ApproveApplicationRequest\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12-\n" +
	"\raudit_comment\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xd0\x0fR\fauditComment\"\x1c\n" +
	"\x1aApproveApplicationResponse\"o\n" +
	"\x18RejectApplicationRequest\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12\"\n" +
	"\x06reason\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xd0\x0fR\x06reason\"\x1b\n" +
	"\x19RejectApplicationResponse\"H\n" +
	"\x15GetApplicationRequest\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\"\xf9\x03\n" +
	"\x16GetApplicationResponse\x12/\n" +
	"\x0eapplication_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rapplicationId\x12B\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1e.merchant.v1.ApplicationStatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x12-\n" +
	"\fcompany_name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vcompanyName\x12*\n" +
	"\vcredit_code\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\n" +
	"creditCode\x12,\n" +
	"\flegal_person\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\vlegalPerson\x12.\n" +
	"\rcontact_phone\x18\x06 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 R\fcontactPhone\x12-\n" +
	"\rreject_reason\x18\a \x01(\tB\b\xbaH\x05r\x03\x18\xd0\x0fR\frejectReason\x12E\n" +
	"\fsubmitted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vsubmittedAt\x12;\n" +
	"\vreviewed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"\x9c\x01\n" +
	"\x17ActivateMerchantRequest\x12*\n" +
	"\vmerchant_id\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18@R\n" +
	"merchantId\x12'\n" +
	"\tshop_name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\bshopName\x12,\n" +
	"\rshop_logo_url\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x10R\vshopLogoUrl\"\x1a\n" +
	"\x18ActivateMerchantResponse*\xc2\x01\n" +
	"\x11ApplicationStatus\x12\"\n" +
	"\x1eAPPLICATION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!APPLICATION_STATUS_PENDING_REVIEW\x10\x01\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_APPROVED\x10\x02\x12\x1f\n" +
	"\x1bAPPLICATION_STATUS_REJECTED\x10\x03\x12 \n" +
	"\x1cAPPLICATION_STATUS_ACTIVATED\x10\x042\x86\x04\n" +
	"\x0fMerchantService\x12d\n" +
	"\x11SubmitApplication\x12%.merchant.v1.SubmitApplicationRequest\x1a&.merchant.v1.SubmitApplicationResponse\"\x00\x12g\n" +
	"\x12ApproveApplication\x12&.merchant.v1.ApproveApplicationRequest\x1a'.merchant.v1.ApproveApplicationResponse\"\x00\x12d\n" +
	"\x11RejectApplication\x12%.merchant.v1.RejectApplicationRequest\x1a&.merchant.v1.RejectApplicationResponse\"\x00\x12[\n" +
	"\x0eGetApplication\x12\".merchant.v1.GetApplicationRequest\x1a#.merchant.v1.GetApplicationResponse\"\x00\x12a\n" +
	"\x10ActivateMerchant\x12$.merchant.v1.ActivateMerchantRequest\x1a%.merchant.v1.ActivateMerchantResponse\"\x00BAZ?github.com/lens077/ecommerce/backend/api/merchant/v1;merchantv1b\x06proto3"

var (
	file_api_merchant_v1_merchant_proto_rawDescOnce sync.Once
	file_api_merchant_v1_merchant_proto_rawDescData []byte
)

func file_api_merchant_v1_merchant_proto_rawDescGZIP() []byte {
	file_api_merchant_v1_merchant_proto_rawDescOnce.Do(func() {
		file_api_merchant_v1_merchant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_merchant_v1_merchant_proto_rawDesc), len(file_api_merchant_v1_merchant_proto_rawDesc)))
	})
	return file_api_merchant_v1_merchant_proto_rawDescData
}

var file_api_merchant_v1_merchant_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_merchant_v1_merchant_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_merchant_v1_merchant_proto_goTypes = []any{
	(ApplicationStatus)(0),             // 0: merchant.v1.ApplicationStatus
	(*SubmitApplicationRequest)(nil),   // 1: merchant.v1.SubmitApplicationRequest
	(*SubmitApplicationResponse)(nil),  // 2: merchant.v1.SubmitApplicationResponse
	(*ApproveApplicationRequest)(nil),  // 3: merchant.v1.ApproveApplicationRequest
	(*ApproveApplicationResponse)(nil), // 4: merchant.v1.ApproveApplicationResponse
	(*RejectApplicationRequest)(nil),   // 5: merchant.v1.RejectApplicationRequest
	(*RejectApplicationResponse)(nil),  // 6: merchant.v1.RejectApplicationResponse
	(*GetApplicationRequest)(nil),      // 7: merchant.v1.GetApplicationRequest
	(*GetApplicationResponse)(nil),     // 8: merchant.v1.GetApplicationResponse
	(*ActivateMerchantRequest)(nil),    // 9: merchant.v1.ActivateMerchantRequest
	(*ActivateMerchantResponse)(nil),   // 10: merchant.v1.ActivateMerchantResponse
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
}
var file_api_merchant_v1_merchant_proto_depIdxs = []int32{
	0,  // 0: merchant.v1.GetApplicationResponse.status:type_name -> merchant.v1.ApplicationStatus
	11, // 1: merchant.v1.GetApplicationResponse.submitted_at:type_name -> google.protobuf.Timestamp
	11, // 2: merchant.v1.GetApplicationResponse.reviewed_at:type_name -> google.protobuf.Timestamp
	1,  // 3: merchant.v1.MerchantService.SubmitApplication:input_type -> merchant.v1.SubmitApplicationRequest
	3,  // 4: merchant.v1.MerchantService.ApproveApplication:input_type -> merchant.v1.ApproveApplicationRequest
	5,  // 5: merchant.v1.MerchantService.RejectApplication:input_type -> merchant.v1.RejectApplicationRequest
	7,  // 6: merchant.v1.MerchantService.GetApplication:input_type -> merchant.v1.GetApplicationRequest
	9,  // 7: merchant.v1.MerchantService.ActivateMerchant:input_type -> merchant.v1.ActivateMerchantRequest
	2,  // 8: merchant.v1.MerchantService.SubmitApplication:output_type -> merchant.v1.SubmitApplicationResponse
	4,  // 9: merchant.v1.MerchantService.ApproveApplication:output_type -> merchant.v1.ApproveApplicationResponse
	6,  // 10: merchant.v1.MerchantService.RejectApplication:output_type -> merchant.v1.RejectApplicationResponse
	8,  // 11: merchant.v1.MerchantService.GetApplication:output_type -> merchant.v1.GetApplicationResponse
	10, // 12: merchant.v1.MerchantService.ActivateMerchant:output_type -> merchant.v1.ActivateMerchantResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_merchant_v1_merchant_proto_init() }
func file_api_merchant_v1_merchant_proto_init() {
	if File_api_merchant_v1_merchant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_merchant_v1_merchant_proto_rawDesc), len(file_api_merchant_v1_merchant_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_merchant_v1_merchant_proto_goTypes,
		DependencyIndexes: file_api_merchant_v1_merchant_proto_depIdxs,
		EnumInfos:         file_api_merchant_v1_merchant_proto_enumTypes,
		MessageInfos:      file_api_merchant_v1_merchant_proto_msgTypes,
	}.Build()
	File_api_merchant_v1_merchant_proto = out.File
	file_api_merchant_v1_merchant_proto_goTypes = nil
	file_api_merchant_v1_merchant_proto_depIdxs = nil
}
