// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const CountRegions = `-- name: CountRegions :one
SELECT count(*)
FROM addresses.regions
`

// 行政区划总数，给启动自检用：表空了说明 seed_regions.sql 没灌
//
//	SELECT count(*)
//	FROM addresses.regions
func (q *Queries) CountRegions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountRegions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateAddress = `-- name: CreateAddress :exec
INSERT INTO addresses.addresses (address_id, user_id, recipient_name, recipient_phone,
                       province, city, district, detail, postal_code, full_text, is_default, is_deleted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, false)
`

type CreateAddressParams struct {
	AddressID      uuid.UUID
	UserID         string
	RecipientName  string
	RecipientPhone string
	Province       string
	City           string
	District       string
	Detail         string
	PostalCode     string
	FullText       string
	IsDefault      bool
}

// 创建地址
//
//	INSERT INTO addresses.addresses (address_id, user_id, recipient_name, recipient_phone,
//	                       province, city, district, detail, postal_code, full_text, is_default, is_deleted)
//	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, false)
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.Exec(ctx, CreateAddress,
		arg.AddressID,
		arg.UserID,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.Province,
		arg.City,
		arg.District,
		arg.Detail,
		arg.PostalCode,
		arg.FullText,
		arg.IsDefault,
	)
	return err
}

const DeleteAddress = `-- name: DeleteAddress :exec
UPDATE addresses.addresses
SET is_deleted = true,
    updated_at = now()
WHERE address_id = $1
`

// 软删除地址
//
//	UPDATE addresses.addresses
//	SET is_deleted = true,
//	    updated_at = now()
//	WHERE address_id = $1
func (q *Queries) DeleteAddress(ctx context.Context, addressID uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteAddress, addressID)
	return err
}

const GetAddressByID = `-- name: GetAddressByID :one
SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
FROM addresses.addresses
WHERE address_id = $1
  AND is_deleted = false
`

// 根据地址ID查询
//
//	SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
//	FROM addresses.addresses
//	WHERE address_id = $1
//	  AND is_deleted = false
func (q *Queries) GetAddressByID(ctx context.Context, addressID uuid.UUID) (AddressesAddress, error) {
	row := q.db.QueryRow(ctx, GetAddressByID, addressID)
	var i AddressesAddress
	err := row.Scan(
		&i.AddressID,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.UserID,
		&i.Province,
		&i.City,
		&i.District,
		&i.Detail,
		&i.PostalCode,
		&i.FullText,
		&i.IsDefault,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDefaultAddressByUserID = `-- name: GetDefaultAddressByUserID :one
SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
FROM addresses.addresses
WHERE user_id = $1
  AND is_default = true
  AND is_deleted = false
LIMIT 1
`

// 查询用户的默认地址
//
//	SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
//	FROM addresses.addresses
//	WHERE user_id = $1
//	  AND is_default = true
//	  AND is_deleted = false
//	LIMIT 1
func (q *Queries) GetDefaultAddressByUserID(ctx context.Context, userID string) (AddressesAddress, error) {
	row := q.db.QueryRow(ctx, GetDefaultAddressByUserID, userID)
	var i AddressesAddress
	err := row.Scan(
		&i.AddressID,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.UserID,
		&i.Province,
		&i.City,
		&i.District,
		&i.Detail,
		&i.PostalCode,
		&i.FullText,
		&i.IsDefault,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListAddressesByUserID = `-- name: ListAddressesByUserID :many
SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
FROM addresses.addresses
WHERE user_id = $1
  AND is_deleted = false
ORDER BY is_default DESC, created_at DESC
`

// 查询用户的所有地址（未删除）
//
//	SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
//	FROM addresses.addresses
//	WHERE user_id = $1
//	  AND is_deleted = false
//	ORDER BY is_default DESC, created_at DESC
func (q *Queries) ListAddressesByUserID(ctx context.Context, userID string) ([]AddressesAddress, error) {
	rows, err := q.db.Query(ctx, ListAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressesAddress
	for rows.Next() {
		var i AddressesAddress
		if err := rows.Scan(
			&i.AddressID,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.UserID,
			&i.Province,
			&i.City,
			&i.District,
			&i.Detail,
			&i.PostalCode,
			&i.FullText,
			&i.IsDefault,
			&i.IsDeleted,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRegionsByParent = `-- name: ListRegionsByParent :many
SELECT id, parent_id, level, code, name, name_en, pinyin, sort_order
FROM addresses.regions
WHERE parent_id = $1
ORDER BY sort_order, id
`

// 按上级列出行政区划（parent_id = 0 即省级）
//
//	SELECT id, parent_id, level, code, name, name_en, pinyin, sort_order
//	FROM addresses.regions
//	WHERE parent_id = $1
//	ORDER BY sort_order, id
func (q *Queries) ListRegionsByParent(ctx context.Context, parentID int32) ([]AddressesRegion, error) {
	rows, err := q.db.Query(ctx, ListRegionsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AddressesRegion
	for rows.Next() {
		var i AddressesRegion
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Level,
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.Pinyin,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SetDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE addresses.addresses
SET is_default = true,
    updated_at = now()
WHERE address_id = $1
  AND is_deleted = false
`

// 设置指定地址为默认
//
//	UPDATE addresses.addresses
//	SET is_default = true,
//	    updated_at = now()
//	WHERE address_id = $1
//	  AND is_deleted = false
func (q *Queries) SetDefaultAddress(ctx context.Context, addressID uuid.UUID) error {
	_, err := q.db.Exec(ctx, SetDefaultAddress, addressID)
	return err
}

const UnsetAllDefaultByUserID = `-- name: UnsetAllDefaultByUserID :exec
UPDATE addresses.addresses
SET is_default = false,
    updated_at = now()
WHERE user_id = $1
  AND is_default = true
  AND is_deleted = false
`

// 设置默认地址（取消用户当前默认，再设置新默认）
//
//	UPDATE addresses.addresses
//	SET is_default = false,
//	    updated_at = now()
//	WHERE user_id = $1
//	  AND is_default = true
//	  AND is_deleted = false
func (q *Queries) UnsetAllDefaultByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, UnsetAllDefaultByUserID, userID)
	return err
}

const UpdateAddress = `-- name: UpdateAddress :exec
UPDATE addresses.addresses
SET recipient_name  = COALESCE($2, recipient_name),
    recipient_phone = COALESCE($3, recipient_phone),
    province        = COALESCE($4, province),
    city            = COALESCE($5, city),
    district        = COALESCE($6, district),
    detail          = COALESCE($7, detail),
    postal_code     = COALESCE($8, postal_code),
    full_text       = COALESCE($9, full_text),
    updated_at      = now()
WHERE address_id = $1
  AND is_deleted = false
`

type UpdateAddressParams struct {
	AddressID      uuid.UUID
	RecipientName  string
	RecipientPhone string
	Province       string
	City           string
	District       string
	Detail         string
	PostalCode     string
	FullText       string
}

// 更新地址信息（仅更新非空字段，由应用层构造）
//
//	UPDATE addresses.addresses
//	SET recipient_name  = COALESCE($2, recipient_name),
//	    recipient_phone = COALESCE($3, recipient_phone),
//	    province        = COALESCE($4, province),
//	    city            = COALESCE($5, city),
//	    district        = COALESCE($6, district),
//	    detail          = COALESCE($7, detail),
//	    postal_code     = COALESCE($8, postal_code),
//	    full_text       = COALESCE($9, full_text),
//	    updated_at      = now()
//	WHERE address_id = $1
//	  AND is_deleted = false
func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.Exec(ctx, UpdateAddress,
		arg.AddressID,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.Province,
		arg.City,
		arg.District,
		arg.Detail,
		arg.PostalCode,
		arg.FullText,
	)
	return err
}
