// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// 行政区划总数，给启动自检用：表空了说明 seed_regions.sql 没灌
	//
	//  SELECT count(*)
	//  FROM addresses.regions
	CountRegions(ctx context.Context) (int64, error)
	// 创建地址
	//
	//  INSERT INTO addresses.addresses (address_id, user_id, recipient_name, recipient_phone,
	//                         province, city, district, detail, postal_code, full_text, is_default, is_deleted)
	//  VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, false)
	CreateAddress(ctx context.Context, arg CreateAddressParams) error
	// 软删除地址
	//
	//  UPDATE addresses.addresses
	//  SET is_deleted = true,
	//      updated_at = now()
	//  WHERE address_id = $1
	DeleteAddress(ctx context.Context, addressID uuid.UUID) error
	// 根据地址ID查询
	//
	//  SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
	//  FROM addresses.addresses
	//  WHERE address_id = $1
	//    AND is_deleted = false
	GetAddressByID(ctx context.Context, addressID uuid.UUID) (AddressesAddress, error)
	// 查询用户的默认地址
	//
	//  SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
	//  FROM addresses.addresses
	//  WHERE user_id = $1
	//    AND is_default = true
	//    AND is_deleted = false
	//  LIMIT 1
	GetDefaultAddressByUserID(ctx context.Context, userID string) (AddressesAddress, error)
	// 查询用户的所有地址（未删除）
	//
	//  SELECT address_id, recipient_name, recipient_phone, user_id, province, city, district, detail, postal_code, full_text, is_default, is_deleted, deleted_at, created_at, updated_at
	//  FROM addresses.addresses
	//  WHERE user_id = $1
	//    AND is_deleted = false
	//  ORDER BY is_default DESC, created_at DESC
	ListAddressesByUserID(ctx context.Context, userID string) ([]AddressesAddress, error)
	// 按上级列出行政区划（parent_id = 0 即省级）
	//
	//  SELECT id, parent_id, level, code, name, name_en, pinyin, sort_order
	//  FROM addresses.regions
	//  WHERE parent_id = $1
	//  ORDER BY sort_order, id
	ListRegionsByParent(ctx context.Context, parentID int32) ([]AddressesRegion, error)
	// 设置指定地址为默认
	//
	//  UPDATE addresses.addresses
	//  SET is_default = true,
	//      updated_at = now()
	//  WHERE address_id = $1
	//    AND is_deleted = false
	SetDefaultAddress(ctx context.Context, addressID uuid.UUID) error
	// 设置默认地址（取消用户当前默认，再设置新默认）
	//
	//  UPDATE addresses.addresses
	//  SET is_default = false,
	//      updated_at = now()
	//  WHERE user_id = $1
	//    AND is_default = true
	//    AND is_deleted = false
	UnsetAllDefaultByUserID(ctx context.Context, userID string) error
	// 更新地址信息（仅更新非空字段，由应用层构造）
	//
	//  UPDATE addresses.addresses
	//  SET recipient_name  = COALESCE($2, recipient_name),
	//      recipient_phone = COALESCE($3, recipient_phone),
	//      province        = COALESCE($4, province),
	//      city            = COALESCE($5, city),
	//      district        = COALESCE($6, district),
	//      detail          = COALESCE($7, detail),
	//      postal_code     = COALESCE($8, postal_code),
	//      full_text       = COALESCE($9, full_text),
	//      updated_at      = now()
	//  WHERE address_id = $1
	//    AND is_deleted = false
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) error
}

var _ Querier = (*Queries)(nil)
