# Preserve pre runtime configuration; prod owns its image selection.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../pre
images:
  - name: ccr.ccs.tencentyun.com/sumery/inventory
    newTag: "1.7.4"
    digest: sha256:d7fe7ce2353ef9201f9172b3eeef7a0a385d3cc9325d48a77e0086f1ef1a48d8
