apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-backend
  namespace: argocd
spec:
  destination:
    namespace: ecommerce
    server: https://kubernetes.default.svc
  project: ecommerce
  source:
    chart: ecommerce-helm
    helm:
      parameters:
      - name: backend.image.tag
        value: 0.1.0
      passCredentials: true
    repoURL: oci://harbor.apikv.com:5443/sumery
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      selfHeal: true
#      prune: true
    syncOptions:
      - CreateNamespace=true
