// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/order/v1/order.proto (package order.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_third_party_validate_validate } from "../../../third_party/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/order/v1/order.proto.
 */
export const file_api_order_v1_order: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvb3JkZXIvdjEvb3JkZXIucHJvdG8SCG9yZGVyLnYxIhQKEkNyZWF0ZU9yZGVyUmVxdWVzdCIVChNDcmVhdGVPcmRlclJlc3BvbnNlIicKFENvbXBsZXRlT3JkZXJSZXF1ZXN0Eg8KB29yZGVyTm8YASABKAkiNwoVQ29tcGxldGVPcmRlclJlc3BvbnNlEh4KBW9yZGVyGAEgASgLMg8ub3JkZXIudjEuT3JkZXIiBwoFT3JkZXIysAEKDG9yZGVyU2VydmljZRJMCgtDcmVhdGVPcmRlchIcLm9yZGVyLnYxLkNyZWF0ZU9yZGVyUmVxdWVzdBodLm9yZGVyLnYxLkNyZWF0ZU9yZGVyUmVzcG9uc2UiABJSCg1Db21wbGV0ZU9yZGVyEh4ub3JkZXIudjEuQ29tcGxldGVPcmRlclJlcXVlc3QaHy5vcmRlci52MS5Db21wbGV0ZU9yZGVyUmVzcG9uc2UiAEKWAQoMY29tLm9yZGVyLnYxQgpPcmRlclByb3RvUAFaOWdpdGh1Yi5jb20vbGVuczA3Ny9lY29tbWVyY2UvYmFja2VuZC9hcGkvb3JkZXIvdjE7b3JkZXJ2MaICA09YWKoCCE9yZGVyLlYxygIIT3JkZXJcVjHiAhRPcmRlclxWMVxHUEJNZXRhZGF0YeoCCU9yZGVyOjpWMWIGcHJvdG8z", [file_third_party_validate_validate]);

/**
 * @generated from message order.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"order.v1.CreateOrderRequest"> & {
};

/**
 * Describes the message order.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 0);

/**
 * @generated from message order.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"order.v1.CreateOrderResponse"> & {
};

/**
 * Describes the message order.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 1);

/**
 * @generated from message order.v1.CompleteOrderRequest
 */
export type CompleteOrderRequest = Message<"order.v1.CompleteOrderRequest"> & {
  /**
   * @generated from field: string orderNo = 1;
   */
  orderNo: string;
};

/**
 * Describes the message order.v1.CompleteOrderRequest.
 * Use `create(CompleteOrderRequestSchema)` to create a new message.
 */
export const CompleteOrderRequestSchema: GenMessage<CompleteOrderRequest> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 2);

/**
 * @generated from message order.v1.CompleteOrderResponse
 */
export type CompleteOrderResponse = Message<"order.v1.CompleteOrderResponse"> & {
  /**
   * @generated from field: order.v1.Order order = 1;
   */
  order?: Order;
};

/**
 * Describes the message order.v1.CompleteOrderResponse.
 * Use `create(CompleteOrderResponseSchema)` to create a new message.
 */
export const CompleteOrderResponseSchema: GenMessage<CompleteOrderResponse> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 3);

/**
 * @generated from message order.v1.Order
 */
export type Order = Message<"order.v1.Order"> & {
};

/**
 * Describes the message order.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 4);

/**
 * @generated from service order.v1.orderService
 */
export const orderService: GenService<{
  /**
   * @generated from rpc order.v1.orderService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
  /**
   * @generated from rpc order.v1.orderService.CompleteOrder
   */
  completeOrder: {
    methodKind: "unary";
    input: typeof CompleteOrderRequestSchema;
    output: typeof CompleteOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_order_v1_order, 0);

