// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file api/order/v1/order.proto (package order.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_third_party_validate_validate } from "../../../third_party/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/order/v1/order.proto.
 */
export const file_api_order_v1_order: GenFile = /*@__PURE__*/
  fileDesc("ChhhcGkvb3JkZXIvdjEvb3JkZXIucHJvdG8SCG9yZGVyLnYxIkwKEkNyZWF0ZU9yZGVyUmVxdWVzdBITCgtDYXJ0SXRlbUlkcxgBIAMoAxIRCglhZGRyZXNzSWQYAiABKAkSDgoGcmVtYXJrGAMgASgJIhUKE0NyZWF0ZU9yZGVyUmVzcG9uc2UiJwoUQ29tcGxldGVPcmRlclJlcXVlc3QSDwoHb3JkZXJObxgBIAEoCSI3ChVDb21wbGV0ZU9yZGVyUmVzcG9uc2USHgoFb3JkZXIYASABKAsyDy5vcmRlci52MS5PcmRlciIHCgVPcmRlcjKwAQoMb3JkZXJTZXJ2aWNlEkwKC0NyZWF0ZU9yZGVyEhwub3JkZXIudjEuQ3JlYXRlT3JkZXJSZXF1ZXN0Gh0ub3JkZXIudjEuQ3JlYXRlT3JkZXJSZXNwb25zZSIAElIKDUNvbXBsZXRlT3JkZXISHi5vcmRlci52MS5Db21wbGV0ZU9yZGVyUmVxdWVzdBofLm9yZGVyLnYxLkNvbXBsZXRlT3JkZXJSZXNwb25zZSIAQpYBCgxjb20ub3JkZXIudjFCCk9yZGVyUHJvdG9QAVo5Z2l0aHViLmNvbS9sZW5zMDc3L2Vjb21tZXJjZS9iYWNrZW5kL2FwaS9vcmRlci92MTtvcmRlcnYxogIDT1hYqgIIT3JkZXIuVjHKAghPcmRlclxWMeICFE9yZGVyXFYxXEdQQk1ldGFkYXRh6gIJT3JkZXI6OlYxYgZwcm90bzM", [file_third_party_validate_validate]);

/**
 * @generated from message order.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"order.v1.CreateOrderRequest"> & {
  /**
   * 用户在购物车中已选商品的唯一标识，订单服务只需知道用户勾选了哪些购物车项
   *
   * @generated from field: repeated int64 CartItemIds = 1;
   */
  CartItemIds: bigint[];

  /**
   * 下单时获取快照。用户可能在提交订单后修改收货地址，但历史订单必须保留当时的地址信息
   *
   * @generated from field: string addressId = 2;
   */
  addressId: string;

  /**
   * @generated from field: string remark = 3;
   */
  remark: string;
};

/**
 * Describes the message order.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 0);

/**
 * @generated from message order.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"order.v1.CreateOrderResponse"> & {
};

/**
 * Describes the message order.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 1);

/**
 * @generated from message order.v1.CompleteOrderRequest
 */
export type CompleteOrderRequest = Message<"order.v1.CompleteOrderRequest"> & {
  /**
   * @generated from field: string orderNo = 1;
   */
  orderNo: string;
};

/**
 * Describes the message order.v1.CompleteOrderRequest.
 * Use `create(CompleteOrderRequestSchema)` to create a new message.
 */
export const CompleteOrderRequestSchema: GenMessage<CompleteOrderRequest> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 2);

/**
 * @generated from message order.v1.CompleteOrderResponse
 */
export type CompleteOrderResponse = Message<"order.v1.CompleteOrderResponse"> & {
  /**
   * @generated from field: order.v1.Order order = 1;
   */
  order?: Order;
};

/**
 * Describes the message order.v1.CompleteOrderResponse.
 * Use `create(CompleteOrderResponseSchema)` to create a new message.
 */
export const CompleteOrderResponseSchema: GenMessage<CompleteOrderResponse> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 3);

/**
 * @generated from message order.v1.Order
 */
export type Order = Message<"order.v1.Order"> & {
};

/**
 * Describes the message order.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_api_order_v1_order, 4);

/**
 * @generated from service order.v1.orderService
 */
export const orderService: GenService<{
  /**
   * @generated from rpc order.v1.orderService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
  /**
   * @generated from rpc order.v1.orderService.CompleteOrder
   */
  completeOrder: {
    methodKind: "unary";
    input: typeof CompleteOrderRequestSchema;
    output: typeof CompleteOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_order_v1_order, 0);

