// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/telemetry/v1/telemetry.proto

// 前端性能遥测采集(Web Vitals + API 耗时)。
//
// 与 behavior.v1 是两个域:behavior 采集的是"用户对内容的行为"(投喂推荐),
// 这里采集的是"页面本身的表现"(投喂可观测性栈)。当前由 behavior 服务进程
// 顺带实现(它已有免鉴权白名单与 sendBeacon 约定),将来 analytics 服务立起来
// 可整体搬走 —— 域已分离,搬走只动部署不动契约。
//
// 数据落点:服务端把 vitals 转成 OTel histogram(→ VictoriaMetrics)与
// 结构化日志(zap → otelzap → Loki),不落业务库。

package telemetryv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebVitalName 与 web-vitals 库的指标名一一对应,外加手写采集的 LONG_TASK。
// value 的单位由指标决定:CLS 是无量纲分数,其余全部是毫秒。
type WebVitalName int32

const (
	WebVitalName_WEB_VITAL_NAME_UNSPECIFIED WebVitalName = 0
	// Largest Contentful Paint,主内容渲染完成时刻(ms)。及格线 2500ms
	WebVitalName_WEB_VITAL_NAME_LCP WebVitalName = 1
	// Cumulative Layout Shift,累积布局偏移(分数)。及格线 0.1
	WebVitalName_WEB_VITAL_NAME_CLS WebVitalName = 2
	// Interaction to Next Paint,全程交互延迟(ms)。及格线 200ms
	WebVitalName_WEB_VITAL_NAME_INP WebVitalName = 3
	// First Contentful Paint,首次内容绘制(ms)。及格线 1800ms
	WebVitalName_WEB_VITAL_NAME_FCP WebVitalName = 4
	// Time to First Byte,首字节时间(ms)。及格线 800ms
	WebVitalName_WEB_VITAL_NAME_TTFB WebVitalName = 5
	// 主线程长任务(ms),手写 PerformanceObserver 采集,无 rating
	WebVitalName_WEB_VITAL_NAME_LONG_TASK WebVitalName = 6
)

// Enum value maps for WebVitalName.
var (
	WebVitalName_name = map[int32]string{
		0: "WEB_VITAL_NAME_UNSPECIFIED",
		1: "WEB_VITAL_NAME_LCP",
		2: "WEB_VITAL_NAME_CLS",
		3: "WEB_VITAL_NAME_INP",
		4: "WEB_VITAL_NAME_FCP",
		5: "WEB_VITAL_NAME_TTFB",
		6: "WEB_VITAL_NAME_LONG_TASK",
	}
	WebVitalName_value = map[string]int32{
		"WEB_VITAL_NAME_UNSPECIFIED": 0,
		"WEB_VITAL_NAME_LCP":         1,
		"WEB_VITAL_NAME_CLS":         2,
		"WEB_VITAL_NAME_INP":         3,
		"WEB_VITAL_NAME_FCP":         4,
		"WEB_VITAL_NAME_TTFB":        5,
		"WEB_VITAL_NAME_LONG_TASK":   6,
	}
)

func (x WebVitalName) Enum() *WebVitalName {
	p := new(WebVitalName)
	*p = x
	return p
}

func (x WebVitalName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebVitalName) Descriptor() protoreflect.EnumDescriptor {
	return file_api_telemetry_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (WebVitalName) Type() protoreflect.EnumType {
	return &file_api_telemetry_v1_telemetry_proto_enumTypes[0]
}

func (x WebVitalName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebVitalName.Descriptor instead.
func (WebVitalName) EnumDescriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

type WebVital struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  WebVitalName           `protobuf:"varint,1,opt,name=name,proto3,enum=telemetry.v1.WebVitalName" json:"name,omitempty"`
	// CLS 是分数(通常 < 1),其余是毫秒。上限 36e5(一小时):再大的值只可能是
	// 客户端时钟错乱,进了 histogram 会把桶分布拉到没法看
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// web-vitals 的三档评级;LONG_TASK 没有评级,留空
	Rating string `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	// 路由模式(如 /product/$spuCode),不是完整 URL —— 它会成为 metric 的
	// attribute,必须低基数。上限对齐 behavior.Event.source 的量级
	Page string `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	// 归因摘要:LCP 的元素 selector、INP 的交互目标、CLS 的最大偏移源、
	// LONG_TASK 的容器(self/iframe)。只进日志不进 metric label
	Attribution string `protobuf:"bytes,5,opt,name=attribution,proto3" json:"attribution,omitempty"`
	TsMs        int64  `protobuf:"varint,6,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	// navigate / reload / back-forward / back-forward-cache / prerender 等,
	// 取自 web-vitals 的 navigationType
	NavType       string `protobuf:"bytes,7,opt,name=nav_type,json=navType,proto3" json:"nav_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebVital) Reset() {
	*x = WebVital{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebVital) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebVital) ProtoMessage() {}

func (x *WebVital) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebVital.ProtoReflect.Descriptor instead.
func (*WebVital) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *WebVital) GetName() WebVitalName {
	if x != nil {
		return x.Name
	}
	return WebVitalName_WEB_VITAL_NAME_UNSPECIFIED
}

func (x *WebVital) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *WebVital) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *WebVital) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *WebVital) GetAttribution() string {
	if x != nil {
		return x.Attribution
	}
	return ""
}

func (x *WebVital) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

func (x *WebVital) GetNavType() string {
	if x != nil {
		return x.NavType
	}
	return ""
}

// ApiTiming 一次 fetch/XHR 的耗时拆解,取自浏览器 Resource Timing。
// 跨域资源没有 Timing-Allow-Origin 时 dns/tcp/ttfb 全是 0,这是浏览器行为,
// 不代表真的为 0 —— 消费侧按 0 值剔除即可。
type ApiTiming struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 已去掉 query 与 origin 的路径。上限对齐 config 域对 URL 类文本的量级
	Path       string  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DurationMs float64 `protobuf:"fixed64,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// 首字节时间(responseStart - requestStart),后端处理慢的信号
	TtfbMs float64 `protobuf:"fixed64,3,opt,name=ttfb_ms,json=ttfbMs,proto3" json:"ttfb_ms,omitempty"`
	DnsMs  float64 `protobuf:"fixed64,4,opt,name=dns_ms,json=dnsMs,proto3" json:"dns_ms,omitempty"`
	TcpMs  float64 `protobuf:"fixed64,5,opt,name=tcp_ms,json=tcpMs,proto3" json:"tcp_ms,omitempty"`
	// encoded body + headers 的传输字节数;跨域无 TAO 时为 0
	TransferSize  int64 `protobuf:"varint,6,opt,name=transfer_size,json=transferSize,proto3" json:"transfer_size,omitempty"`
	TsMs          int64 `protobuf:"varint,7,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiTiming) Reset() {
	*x = ApiTiming{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiTiming) ProtoMessage() {}

func (x *ApiTiming) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiTiming.ProtoReflect.Descriptor instead.
func (*ApiTiming) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ApiTiming) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ApiTiming) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ApiTiming) GetTtfbMs() float64 {
	if x != nil {
		return x.TtfbMs
	}
	return 0
}

func (x *ApiTiming) GetDnsMs() float64 {
	if x != nil {
		return x.DnsMs
	}
	return 0
}

func (x *ApiTiming) GetTcpMs() float64 {
	if x != nil {
		return x.TcpMs
	}
	return 0
}

func (x *ApiTiming) GetTransferSize() int64 {
	if x != nil {
		return x.TransferSize
	}
	return 0
}

func (x *ApiTiming) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type CollectWebVitalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 匿名标识。登录用户由网关注入的 x-md-global-user-id 覆盖 —— 与 Track 同约定
	AnonId    string `protobuf:"bytes,1,opt,name=anon_id,json=anonId,proto3" json:"anon_id,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 一次页面生命周期最多产生 5 个核心指标 + 若干 LONG_TASK,50 足够;
	// 超出说明客户端逻辑有 bug,拒收比收下更能暴露问题
	Vitals []*WebVital `protobuf:"bytes,3,rep,name=vitals,proto3" json:"vitals,omitempty"`
	// 批量上批的 API 耗时,上限对齐 Track.events 的 max_items
	ApiTimings    []*ApiTiming `protobuf:"bytes,4,rep,name=api_timings,json=apiTimings,proto3" json:"api_timings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectWebVitalsRequest) Reset() {
	*x = CollectWebVitalsRequest{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectWebVitalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectWebVitalsRequest) ProtoMessage() {}

func (x *CollectWebVitalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectWebVitalsRequest.ProtoReflect.Descriptor instead.
func (*CollectWebVitalsRequest) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *CollectWebVitalsRequest) GetAnonId() string {
	if x != nil {
		return x.AnonId
	}
	return ""
}

func (x *CollectWebVitalsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CollectWebVitalsRequest) GetVitals() []*WebVital {
	if x != nil {
		return x.Vitals
	}
	return nil
}

func (x *CollectWebVitalsRequest) GetApiTimings() []*ApiTiming {
	if x != nil {
		return x.ApiTimings
	}
	return nil
}

type CollectWebVitalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint32                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectWebVitalsResponse) Reset() {
	*x = CollectWebVitalsResponse{}
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectWebVitalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectWebVitalsResponse) ProtoMessage() {}

func (x *CollectWebVitalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_telemetry_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectWebVitalsResponse.ProtoReflect.Descriptor instead.
func (*CollectWebVitalsResponse) Descriptor() ([]byte, []int) {
	return file_api_telemetry_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *CollectWebVitalsResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_api_telemetry_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_telemetry_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	" api/telemetry/v1/telemetry.proto\x12\ftelemetry.v1\x1a#third_party/validate/validate.proto\"\xc3\x02\n" +
	"\bWebVital\x12:\n" +
	"\x04name\x18\x01 \x01(\x0e2\x1a.telemetry.v1.WebVitalNameB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04name\x12/\n" +
	"\x05value\x18\x02 \x01(\x01B\x19\xbaH\x16\x12\x14@\x01\x19\x00\x00\x00\x00@wKA)\x00\x00\x00\x00\x00\x00\x00\x00R\x05value\x12>\n" +
	"\x06rating\x18\x03 \x01(\tB&\xbaH#r!R\x00R\x04goodR\x11needs-improvementR\x04poorR\x06rating\x12\x1c\n" +
	"\x04page\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x04page\x12*\n" +
	"\vattribution\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vattribution\x12\x1c\n" +
	"\x05ts_ms\x18\x06 \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x04tsMs\x12\"\n" +
	"\bnav_type\x18\a \x01(\tB\a\xbaH\x04r\x02\x18 R\anavType\"\xd1\x02\n" +
	"\tApiTiming\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x04path\x12:\n" +
	"\vduration_ms\x18\x02 \x01(\x01B\x19\xbaH\x16\x12\x14@\x01\x19\x00\x00\x00\x00@wKA)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"durationMs\x122\n" +
	"\attfb_ms\x18\x03 \x01(\x01B\x19\xbaH\x16\x12\x14@\x01\x19\x00\x00\x00\x00@wKA)\x00\x00\x00\x00\x00\x00\x00\x00R\x06ttfbMs\x120\n" +
	"\x06dns_ms\x18\x04 \x01(\x01B\x19\xbaH\x16\x12\x14@\x01\x19\x00\x00\x00\x00@wKA)\x00\x00\x00\x00\x00\x00\x00\x00R\x05dnsMs\x120\n" +
	"\x06tcp_ms\x18\x05 \x01(\x01B\x19\xbaH\x16\x12\x14@\x01\x19\x00\x00\x00\x00@wKA)\x00\x00\x00\x00\x00\x00\x00\x00R\x05tcpMs\x122\n" +
	"\rtransfer_size\x18\x06 \x01(\x03B\r\xbaH\n" +
	"\"\b\x18\x80\x80\x80\x80\x04(\x00R\ftransferSize\x12\x1c\n" +
	"\x05ts_ms\x18\a \x01(\x03B\a\xbaH\x04\"\x02(\x00R\x04tsMs\"\xe2\x01\n" +
	"\x17CollectWebVitalsRequest\x12 \n" +
	"\aanon_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x18@R\x06anonId\x12&\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\tsessionId\x128\n" +
	"\x06vitals\x18\x03 \x03(\v2\x16.telemetry.v1.WebVitalB\b\xbaH\x05\x92\x01\x02\x102R\x06vitals\x12C\n" +
	"\vapi_timings\x18\x04 \x03(\v2\x17.telemetry.v1.ApiTimingB\t\xbaH\x06\x92\x01\x03\x10\xc8\x01R\n" +
	"apiTimings\"@\n" +
	"\x18CollectWebVitalsResponse\x12$\n" +
	"\baccepted\x18\x01 \x01(\rB\b\xbaH\x05*\x03\x18\xfa\x01R\baccepted*\xc5\x01\n" +
	"\fWebVitalName\x12\x1e\n" +
	"\x1aWEB_VITAL_NAME_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WEB_VITAL_NAME_LCP\x10\x01\x12\x16\n" +
	"\x12WEB_VITAL_NAME_CLS\x10\x02\x12\x16\n" +
	"\x12WEB_VITAL_NAME_INP\x10\x03\x12\x16\n" +
	"\x12WEB_VITAL_NAME_FCP\x10\x04\x12\x17\n" +
	"\x13WEB_VITAL_NAME_TTFB\x10\x05\x12\x1c\n" +
	"\x18WEB_VITAL_NAME_LONG_TASK\x10\x062w\n" +
	"\x10TelemetryService\x12c\n" +
	"\x10CollectWebVitals\x12%.telemetry.v1.CollectWebVitalsRequest\x1a&.telemetry.v1.CollectWebVitalsResponse\"\x00BCZAgithub.com/lens077/ecommerce/backend/api/telemetry/v1;telemetryv1b\x06proto3"

var (
	file_api_telemetry_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_telemetry_v1_telemetry_proto_rawDescData []byte
)

func file_api_telemetry_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_telemetry_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_telemetry_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telemetry_v1_telemetry_proto_rawDesc), len(file_api_telemetry_v1_telemetry_proto_rawDesc)))
	})
	return file_api_telemetry_v1_telemetry_proto_rawDescData
}

var file_api_telemetry_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_telemetry_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_telemetry_v1_telemetry_proto_goTypes = []any{
	(WebVitalName)(0),                // 0: telemetry.v1.WebVitalName
	(*WebVital)(nil),                 // 1: telemetry.v1.WebVital
	(*ApiTiming)(nil),                // 2: telemetry.v1.ApiTiming
	(*CollectWebVitalsRequest)(nil),  // 3: telemetry.v1.CollectWebVitalsRequest
	(*CollectWebVitalsResponse)(nil), // 4: telemetry.v1.CollectWebVitalsResponse
}
var file_api_telemetry_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.WebVital.name:type_name -> telemetry.v1.WebVitalName
	1, // 1: telemetry.v1.CollectWebVitalsRequest.vitals:type_name -> telemetry.v1.WebVital
	2, // 2: telemetry.v1.CollectWebVitalsRequest.api_timings:type_name -> telemetry.v1.ApiTiming
	3, // 3: telemetry.v1.TelemetryService.CollectWebVitals:input_type -> telemetry.v1.CollectWebVitalsRequest
	4, // 4: telemetry.v1.TelemetryService.CollectWebVitals:output_type -> telemetry.v1.CollectWebVitalsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_telemetry_v1_telemetry_proto_init() }
func file_api_telemetry_v1_telemetry_proto_init() {
	if File_api_telemetry_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telemetry_v1_telemetry_proto_rawDesc), len(file_api_telemetry_v1_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_telemetry_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_telemetry_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_api_telemetry_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_api_telemetry_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_telemetry_v1_telemetry_proto = out.File
	file_api_telemetry_v1_telemetry_proto_goTypes = nil
	file_api_telemetry_v1_telemetry_proto_depIdxs = nil
}
