replicaCount: 1
enabled: true

global:
  configSource:
    enabled: true
    secretName: ecommerce-config-source-pre
    mountPath: /etc/ecommerce/config-source

image:
  repository: "ccr.ccs.tencentyun.com/sumery/payment"
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    http:
      enabled: true
      port: 30013
      targetPort: 30013
    grpc:
      enabled: false
      port: 30014
      targetPort: 30014

env: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi
