/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as PaymentResultRouteImport } from './routes/payment/result'
import { Route as ProductSpuCodeRouteImport } from './routes/product/$spuCode'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileAddressesIndexRouteImport } from './routes/profile/addresses/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment/result',
  path: '/payment/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSpuCodeRoute = ProductSpuCodeRouteImport.update({
  id: '/product/$spuCode',
  path: '/product/$spuCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesIndexRoute = ProfileAddressesIndexRouteImport.update({
  id: '/profile/addresses/',
  path: '/profile/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payment/result': typeof PaymentResultRoute
  '/product/$spuCode': typeof ProductSpuCodeRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/addresses/': typeof ProfileAddressesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payment/result': typeof PaymentResultRoute
  '/product/$spuCode': typeof ProductSpuCodeRoute
  '/cart': typeof CartIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/addresses': typeof ProfileAddressesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/payment/result': typeof PaymentResultRoute
  '/product/$spuCode': typeof ProductSpuCodeRoute
  '/cart/': typeof CartIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/addresses/': typeof ProfileAddressesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/orders/$orderId'
    | '/payment/result'
    | '/product/$spuCode'
    | '/cart/'
    | '/categories/'
    | '/checkout/'
    | '/orders/'
    | '/profile/'
    | '/profile/addresses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/orders/$orderId'
    | '/payment/result'
    | '/product/$spuCode'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/profile'
    | '/profile/addresses'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/orders/$orderId'
    | '/payment/result'
    | '/product/$spuCode'
    | '/cart/'
    | '/categories/'
    | '/checkout/'
    | '/orders/'
    | '/profile/'
    | '/profile/addresses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  PaymentResultRoute: typeof PaymentResultRoute
  ProductSpuCodeRoute: typeof ProductSpuCodeRoute
  CartIndexRoute: typeof CartIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileAddressesIndexRoute: typeof ProfileAddressesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/result': {
      id: '/payment/result'
      path: '/payment/result'
      fullPath: '/payment/result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$spuCode': {
      id: '/product/$spuCode'
      path: '/product/$spuCode'
      fullPath: '/product/$spuCode'
      preLoaderRoute: typeof ProductSpuCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses/': {
      id: '/profile/addresses/'
      path: '/profile/addresses'
      fullPath: '/profile/addresses/'
      preLoaderRoute: typeof ProfileAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  PaymentResultRoute: PaymentResultRoute,
  ProductSpuCodeRoute: ProductSpuCodeRoute,
  CartIndexRoute: CartIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileAddressesIndexRoute: ProfileAddressesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
