// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentsPayment struct {
	ID               int64
	OrderID          int64
	ConsumerID       uuid.UUID
	Amount           pgtype.Numeric
	Currency         string
	Method           string
	Status           string
	Subject          string
	TradeNo          string
	FreezeID         int64
	ConsumerVersion  int64
	MerchantVersions int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
